import { NextRequest, NextResponse } from "next/server";
import { CREEM } from "@/lib/site";
import { getProduct, isBuyable, PRICING_VARIANT } from "@/lib/products";
import { isValidEmail } from "@/lib/mail";
import { recordPendingCheckout } from "@/lib/pending";

// Checkout sessions are created server-side so the Creem API key stays secret.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface Body {
  /** Creem product id for the chosen plan */
  productId?: string;
  /** license key generated by the extension / pricing panel */
  key?: string;
  /** where to deliver the license key */
  email?: string;
}

export async function POST(req: NextRequest) {
  if (!CREEM.apiKey) {
    return NextResponse.json(
      { error: "Checkout is not configured yet." },
      { status: 503 }
    );
  }

  let body: Body;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid json" }, { status: 400 });
  }

  const key = body.key?.trim();
  const productId = body.productId?.trim();
  const email = body.email?.trim().toLowerCase() || "";
  if (!key || !productId) {
    return NextResponse.json(
      { error: "key and productId are required" },
      { status: 400 }
    );
  }
  if (!email || !isValidEmail(email)) {
    return NextResponse.json(
      { error: "Please enter a valid email address." },
      { status: 400 }
    );
  }

  // Never trust the client's product id blindly — it must be one we sell.
  // isBuyable is the single authority on what may be sold: it already accounts
  // for retired products, placeholder ids, and the lifetime-only rollback.
  const product = getProduct(productId);
  if (!product || !isBuyable(product)) {
    return NextResponse.json({ error: "unknown product" }, { status: 400 });
  }

  const extension = "cleanmysocial"; // licence group — one record per key
  // Every product is a single extension now; the useful distinction is how it
  // is billed, which is what support and the Vault rows want to see.
  const plan = product.access === "pass"
    ? "hot"
    : product.access === "subscription"
      ? "monthly"
      : "lifetime";

  // Creem appends the signed request_id / checkout_id / product_id parameters.
  // Keep this URL free of our own query parameters so its prescribed signing
  // order can be verified exactly by the success-page fulfillment fallback.
  const origin = new URL(req.url).origin;
  const successUrl = `${origin}/success`;

  try {
    const res = await fetch(`${CREEM.apiUrl}/checkouts`, {
      method: "POST",
      headers: {
        "x-api-key": CREEM.apiKey,
        "Content-Type": "application/json",
      },
      cache: "no-store",
      body: JSON.stringify({
        product_id: productId,
        request_id: key,
        success_url: successUrl,
        // Prefill Creem's checkout so the buyer pays with the same address the
        // license is mailed to, instead of typing it twice.
        customer: { email },
        // Echoed back verbatim on every webhook event — this is how the
        // webhook attributes the payment to a license and knows where to send
        // the key.
        metadata: {
          key,
          extension,
          license_group: extension,
          extension_slug:
            product.entitlements.length === 1 ? product.entitlements[0] : "cleanmysocial",
          plan,
          email,
          product_id: product.id,
          entitlements: product.entitlements.join(","),
          billing_type: product.billingType,
          billing_period: product.billingPeriod,
          access: product.access,
          pricing_variant: PRICING_VARIANT,
          access_duration_days: product.durationDays || undefined,
        },
      }),
    });

    const data = (await res.json()) as { checkout_url?: string; message?: unknown };
    if (!res.ok || !data.checkout_url) {
      console.error("[creem] checkout create failed", res.status, data);
      return NextResponse.json(
        { error: "Could not start checkout. Please try again." },
        { status: 502 }
      );
    }

    // Remember the attempt so an unfinished checkout can be followed up on.
    // Never let bookkeeping block the buyer from reaching Creem.
    try {
      await recordPendingCheckout({ key, email, extension, plan, productId: product.id });
    } catch (e) {
      console.error("[creem] could not record pending checkout", e);
    }

    return NextResponse.json({ url: data.checkout_url });
  } catch (e) {
    console.error("[creem] checkout error", e);
    return NextResponse.json(
      { error: "Could not start checkout. Please try again." },
      { status: 502 }
    );
  }
}
