import { NextRequest, NextResponse } from "next/server";
import { CREEM } from "@/lib/site";
import { findByProductId, groupOf } from "@/lib/extensions";

// Checkout sessions are created server-side so the Creem API key stays secret.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface Body {
  /** Creem product id for the chosen plan */
  productId?: string;
  /** license key generated by the extension / pricing panel */
  key?: string;
}

export async function POST(req: NextRequest) {
  if (!CREEM.apiKey) {
    return NextResponse.json(
      { error: "Checkout is not configured yet." },
      { status: 503 }
    );
  }

  let body: Body;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid json" }, { status: 400 });
  }

  const key = body.key?.trim();
  const productId = body.productId?.trim();
  if (!key || !productId) {
    return NextResponse.json(
      { error: "key and productId are required" },
      { status: 400 }
    );
  }

  // Never trust the client's product id blindly — it must map to a known plan.
  const mapped = findByProductId(productId);
  if (!mapped) {
    return NextResponse.json({ error: "unknown product" }, { status: 400 });
  }

  const extension = groupOf(mapped.extension); // license group
  const plan = mapped.plan.plan;

  // Success page shows the key as a restore code; Creem also appends its own
  // request_id / checkout_id / order_id / signature params to this URL.
  const origin = new URL(req.url).origin;
  const successUrl = `${origin}/success?lk=${encodeURIComponent(key)}`;

  try {
    const res = await fetch(`${CREEM.apiUrl}/checkouts`, {
      method: "POST",
      headers: {
        "x-api-key": CREEM.apiKey,
        "Content-Type": "application/json",
      },
      cache: "no-store",
      body: JSON.stringify({
        product_id: productId,
        request_id: key,
        success_url: successUrl,
        // Echoed back verbatim on every webhook event — this is how the
        // webhook attributes the payment to a license.
        metadata: { key, extension, plan },
      }),
    });

    const data = (await res.json()) as { checkout_url?: string; message?: unknown };
    if (!res.ok || !data.checkout_url) {
      console.error("[creem] checkout create failed", res.status, data);
      return NextResponse.json(
        { error: "Could not start checkout. Please try again." },
        { status: 502 }
      );
    }

    return NextResponse.json({ url: data.checkout_url });
  } catch (e) {
    console.error("[creem] checkout error", e);
    return NextResponse.json(
      { error: "Could not start checkout. Please try again." },
      { status: 502 }
    );
  }
}
