import type { Locale } from "./locales";

const EN = {
  pinFromExtensions: "Pin from Extensions",
  installed: "Installed",
  ready: "{name} is ready.",
  pinInstruction: "Pin it from Chrome’s Extensions menu, then open {platform}.",
  open: "Open {platform}",
  readyWhen: "Ready when you are",
  privacyDesign: "Privacy by design",
  dataBrowser: "Your data stays in your browser.",
  seeAccess: "See exactly what it accesses →",
  independent: "Independent tools for a quieter social life.",
  support: "Support",
  privacy: "Privacy",
  more: "More from CleanMySocial",
  explore: "Explore →",
  free: "Free",
  anonymousFeedback: "Anonymous feedback",
  extensionUninstalled: "Extension uninstalled",
  thanksTry: "Before you go…",
  uninstallQuestion: "Why did you uninstall {name}?",
  oneAnswer: "Choose one reason—we may be able to help.",
  reinstall: "Reinstall {name} ↗",
  whatHappened: "What happened?",
  chooseReason: "Choose the closest reason",
  reasonNotWorking: "It didn’t work",
  reasonHard: "It was difficult to use",
  reasonMissing: "A feature was missing",
  reasonPrivacy: "Privacy or permissions",
  reasonNoNeed: "I don’t need it anymore",
  reasonOther: "Something else",
  anythingElse: "Anything else?",
  optional: "Optional",
  notePlaceholder: "A short note can help us understand the problem.",
  selectReasonNote: "Select a reason to add an optional note.",
  sending: "Sending…",
  sendFeedback: "Send feedback",
  skipFeedback: "Skip feedback",
  anonymousNotice: "Anonymous · please don’t include personal information",
  sendError: "Couldn’t send that. Please try once more.",
  feedbackReceived: "Feedback received",
  feedbackSkipped: "Feedback skipped",
  thanksHelps: "Thanks—that helps.",
  noProblem: "No problem.",
  sentAnonymously: "Your response was sent anonymously.",
  nothingSent: "Nothing was sent or stored.",
  exploreAll: "Explore all →",
} as const;

export type LifecycleCopy = { [Key in keyof typeof EN]: string };

const TRANSLATIONS: Partial<Record<Exclude<Locale, "en">, LifecycleCopy>> = {
  de: {
    pinFromExtensions: "Über Erweiterungen anheften", installed: "Installiert", ready: "{name} ist bereit.",
    pinInstruction: "Hefte die Erweiterung im Chrome-Menü an und öffne dann {platform}.", open: "{platform} öffnen",
    readyWhen: "Bereit, wenn du es bist", privacyDesign: "Datenschutz von Anfang an", dataBrowser: "Deine Daten bleiben in deinem Browser.",
    seeAccess: "Genau ansehen, worauf zugegriffen wird →", independent: "Unabhängige Tools für ein ruhigeres Social-Media-Leben.",
    support: "Support", privacy: "Datenschutz", more: "Mehr von CleanMySocial", explore: "Entdecken →", free: "Kostenlos",
    anonymousFeedback: "Anonymes Feedback", extensionUninstalled: "Erweiterung deinstalliert", thanksTry: "Bevor du gehst…",
    uninstallQuestion: "Warum hast du {name} deinstalliert?", oneAnswer: "Wähle einen Grund – vielleicht können wir helfen.", reinstall: "{name} neu installieren ↗",
    whatHappened: "Was ist passiert?", chooseReason: "Wähle den passendsten Grund", reasonNotWorking: "Es hat nicht funktioniert",
    reasonHard: "Die Bedienung war schwierig", reasonMissing: "Eine Funktion hat gefehlt", reasonPrivacy: "Datenschutz oder Berechtigungen",
    reasonNoNeed: "Ich brauche es nicht mehr", reasonOther: "Etwas anderes", anythingElse: "Noch etwas?", optional: "Optional",
    notePlaceholder: "Eine kurze Notiz hilft uns, das Problem zu verstehen.", selectReasonNote: "Wähle einen Grund, um optional eine Notiz hinzuzufügen.",
    sending: "Wird gesendet…", sendFeedback: "Feedback senden", skipFeedback: "Feedback überspringen",
    anonymousNotice: "Anonym · bitte keine persönlichen Daten angeben", sendError: "Senden fehlgeschlagen. Bitte versuche es noch einmal.",
    feedbackReceived: "Feedback erhalten", feedbackSkipped: "Feedback übersprungen", thanksHelps: "Danke — das hilft.", noProblem: "Kein Problem.",
    sentAnonymously: "Deine Antwort wurde anonym gesendet.", nothingSent: "Es wurde nichts gesendet oder gespeichert.", exploreAll: "Alle entdecken →",
  },
  ja: {
    pinFromExtensions: "拡張機能から固定", installed: "インストール済み", ready: "{name} の準備ができました。",
    pinInstruction: "Chrome の拡張機能メニューから固定し、{platform} を開いてください。", open: "{platform} を開く",
    readyWhen: "いつでも開始できます", privacyDesign: "プライバシー重視の設計", dataBrowser: "データはブラウザ内に留まります。",
    seeAccess: "アクセス内容を確認 →", independent: "SNS をもっと静かにする独立系ツール。", support: "サポート", privacy: "プライバシー",
    more: "CleanMySocial のその他のツール", explore: "見る →", free: "無料", anonymousFeedback: "匿名フィードバック",
    extensionUninstalled: "拡張機能をアンインストールしました", thanksTry: "その前に…",
    uninstallQuestion: "{name} をアンインストールした理由を教えてください。", oneAnswer: "理由を一つ選んでください。お手伝いできるかもしれません。", reinstall: "{name} を再インストール ↗",
    whatHappened: "何がありましたか？", chooseReason: "最も近い理由を選択", reasonNotWorking: "動作しなかった",
    reasonHard: "使いにくかった", reasonMissing: "必要な機能がなかった", reasonPrivacy: "プライバシーまたは権限",
    reasonNoNeed: "もう必要ない", reasonOther: "その他", anythingElse: "ほかにありますか？", optional: "任意",
    notePlaceholder: "短いメモが問題の理解に役立ちます。", selectReasonNote: "理由を選ぶと任意のメモを追加できます。",
    sending: "送信中…", sendFeedback: "フィードバックを送信", skipFeedback: "スキップ",
    anonymousNotice: "匿名です · 個人情報は入力しないでください", sendError: "送信できませんでした。もう一度お試しください。",
    feedbackReceived: "フィードバックを受け取りました", feedbackSkipped: "フィードバックをスキップしました", thanksHelps: "ありがとうございます。参考になります。",
    noProblem: "問題ありません。", sentAnonymously: "回答は匿名で送信されました。", nothingSent: "送信・保存された情報はありません。", exploreAll: "すべて見る →",
  },
  fr: {
    pinFromExtensions: "Épingler depuis Extensions", installed: "Installée", ready: "{name} est prête.",
    pinInstruction: "Épinglez-la depuis le menu Extensions de Chrome, puis ouvrez {platform}.", open: "Ouvrir {platform}",
    readyWhen: "Prête quand vous l’êtes", privacyDesign: "Confidentialité intégrée", dataBrowser: "Vos données restent dans votre navigateur.",
    seeAccess: "Voir précisément ses accès →", independent: "Des outils indépendants pour des réseaux sociaux plus calmes.", support: "Assistance",
    privacy: "Confidentialité", more: "Plus de CleanMySocial", explore: "Découvrir →", free: "Gratuit", anonymousFeedback: "Avis anonyme",
    extensionUninstalled: "Extension désinstallée", thanksTry: "Avant de partir…", uninstallQuestion: "Pourquoi avez-vous désinstallé {name} ?",
    oneAnswer: "Choisissez une raison — nous pourrons peut-être vous aider.", reinstall: "Réinstaller {name} ↗", whatHappened: "Que s’est-il passé ?",
    chooseReason: "Choisissez la raison la plus proche", reasonNotWorking: "Elle ne fonctionnait pas", reasonHard: "Elle était difficile à utiliser",
    reasonMissing: "Une fonctionnalité manquait", reasonPrivacy: "Confidentialité ou autorisations", reasonNoNeed: "Je n’en ai plus besoin",
    reasonOther: "Autre chose", anythingElse: "Autre chose à ajouter ?", optional: "Facultatif",
    notePlaceholder: "Une courte note peut nous aider à comprendre le problème.", selectReasonNote: "Choisissez une raison pour ajouter une note facultative.",
    sending: "Envoi…", sendFeedback: "Envoyer l’avis", skipFeedback: "Ignorer", anonymousNotice: "Anonyme · n’indiquez aucune donnée personnelle",
    sendError: "Envoi impossible. Veuillez réessayer.", feedbackReceived: "Avis reçu", feedbackSkipped: "Avis ignoré", thanksHelps: "Merci, cela nous aide.",
    noProblem: "Aucun problème.", sentAnonymously: "Votre réponse a été envoyée anonymement.", nothingSent: "Rien n’a été envoyé ni enregistré.", exploreAll: "Tout découvrir →",
  },
  ko: {
    pinFromExtensions: "확장 프로그램에서 고정", installed: "설치됨", ready: "{name}을 사용할 준비가 되었습니다.",
    pinInstruction: "Chrome 확장 프로그램 메뉴에서 고정한 다음 {platform}을 여세요.", open: "{platform} 열기", readyWhen: "언제든 시작하세요",
    privacyDesign: "개인정보 보호 중심 설계", dataBrowser: "데이터는 브라우저 안에만 보관됩니다.", seeAccess: "접근 항목 자세히 보기 →",
    independent: "더 조용한 소셜 생활을 위한 독립 도구.", support: "지원", privacy: "개인정보", more: "CleanMySocial의 다른 도구",
    explore: "살펴보기 →", free: "무료", anonymousFeedback: "익명 피드백", extensionUninstalled: "확장 프로그램 제거됨",
    thanksTry: "가기 전에…", uninstallQuestion: "{name}을 제거한 이유는 무엇인가요?", oneAnswer: "이유를 하나 선택해 주세요. 도와드릴 수 있을지도 몰라요.",
    reinstall: "{name} 다시 설치 ↗", whatHappened: "무슨 일이 있었나요?", chooseReason: "가장 가까운 이유 선택", reasonNotWorking: "작동하지 않았어요",
    reasonHard: "사용하기 어려웠어요", reasonMissing: "필요한 기능이 없었어요", reasonPrivacy: "개인정보 또는 권한",
    reasonNoNeed: "더 이상 필요하지 않아요", reasonOther: "기타", anythingElse: "추가로 알려주실 내용이 있나요?", optional: "선택 사항",
    notePlaceholder: "짧은 메모가 문제를 이해하는 데 도움이 됩니다.", selectReasonNote: "이유를 선택하면 선택적으로 메모를 추가할 수 있습니다.",
    sending: "전송 중…", sendFeedback: "피드백 보내기", skipFeedback: "피드백 건너뛰기", anonymousNotice: "익명 · 개인정보를 포함하지 마세요",
    sendError: "전송하지 못했습니다. 다시 시도해 주세요.", feedbackReceived: "피드백 접수됨", feedbackSkipped: "피드백 건너뜀",
    thanksHelps: "감사합니다. 도움이 됩니다.", noProblem: "괜찮습니다.", sentAnonymously: "응답이 익명으로 전송되었습니다.", nothingSent: "전송되거나 저장된 내용이 없습니다.", exploreAll: "모두 보기 →",
  },
  nl: {
    pinFromExtensions: "Vastmaken via Extensies", installed: "Geïnstalleerd", ready: "{name} is klaar.",
    pinInstruction: "Maak de extensie vast via Chrome Extensies en open daarna {platform}.", open: "{platform} openen", readyWhen: "Klaar wanneer jij dat bent",
    privacyDesign: "Privacy vanaf het ontwerp", dataBrowser: "Je gegevens blijven in je browser.", seeAccess: "Bekijk precies waartoe het toegang heeft →",
    independent: "Onafhankelijke tools voor een rustiger sociaal leven.", support: "Ondersteuning", privacy: "Privacy", more: "Meer van CleanMySocial",
    explore: "Bekijken →", free: "Gratis", anonymousFeedback: "Anonieme feedback", extensionUninstalled: "Extensie verwijderd",
    thanksTry: "Voordat je gaat…", uninstallQuestion: "Waarom heb je {name} verwijderd?", oneAnswer: "Kies één reden — misschien kunnen we helpen.",
    reinstall: "{name} opnieuw installeren ↗", whatHappened: "Wat is er gebeurd?", chooseReason: "Kies de best passende reden",
    reasonNotWorking: "Het werkte niet", reasonHard: "Het was moeilijk te gebruiken", reasonMissing: "Er ontbrak een functie",
    reasonPrivacy: "Privacy of machtigingen", reasonNoNeed: "Ik heb het niet meer nodig", reasonOther: "Iets anders", anythingElse: "Nog iets?", optional: "Optioneel",
    notePlaceholder: "Een korte toelichting helpt ons het probleem te begrijpen.", selectReasonNote: "Kies een reden om optioneel een toelichting toe te voegen.",
    sending: "Verzenden…", sendFeedback: "Feedback verzenden", skipFeedback: "Feedback overslaan", anonymousNotice: "Anoniem · vermeld geen persoonlijke gegevens",
    sendError: "Verzenden is mislukt. Probeer het opnieuw.", feedbackReceived: "Feedback ontvangen", feedbackSkipped: "Feedback overgeslagen",
    thanksHelps: "Bedankt, dat helpt.", noProblem: "Geen probleem.", sentAnonymously: "Je antwoord is anoniem verzonden.", nothingSent: "Er is niets verzonden of opgeslagen.", exploreAll: "Alles bekijken →",
  },
  it: {
    pinFromExtensions: "Fissa da Estensioni", installed: "Installata", ready: "{name} è pronta.",
    pinInstruction: "Fissala dal menu Estensioni di Chrome, poi apri {platform}.", open: "Apri {platform}", readyWhen: "Pronta quando vuoi",
    privacyDesign: "Privacy fin dalla progettazione", dataBrowser: "I tuoi dati restano nel browser.", seeAccess: "Scopri esattamente a cosa accede →",
    independent: "Strumenti indipendenti per una vita social più tranquilla.", support: "Assistenza", privacy: "Privacy", more: "Altro da CleanMySocial",
    explore: "Scopri →", free: "Gratis", anonymousFeedback: "Feedback anonimo", extensionUninstalled: "Estensione disinstallata",
    thanksTry: "Prima di andare…", uninstallQuestion: "Perché hai disinstallato {name}?", oneAnswer: "Scegli un motivo: forse possiamo aiutarti.",
    reinstall: "Reinstalla {name} ↗", whatHappened: "Che cosa è successo?", chooseReason: "Scegli il motivo più vicino",
    reasonNotWorking: "Non funzionava", reasonHard: "Era difficile da usare", reasonMissing: "Mancava una funzione", reasonPrivacy: "Privacy o autorizzazioni",
    reasonNoNeed: "Non mi serve più", reasonOther: "Altro", anythingElse: "Vuoi aggiungere altro?", optional: "Facoltativo",
    notePlaceholder: "Una breve nota può aiutarci a capire il problema.", selectReasonNote: "Scegli un motivo per aggiungere una nota facoltativa.",
    sending: "Invio…", sendFeedback: "Invia feedback", skipFeedback: "Salta feedback", anonymousNotice: "Anonimo · non includere informazioni personali",
    sendError: "Invio non riuscito. Riprova.", feedbackReceived: "Feedback ricevuto", feedbackSkipped: "Feedback saltato", thanksHelps: "Grazie, ci aiuta.",
    noProblem: "Nessun problema.", sentAnonymously: "La risposta è stata inviata in forma anonima.", nothingSent: "Nulla è stato inviato o salvato.", exploreAll: "Scopri tutto →",
  },
  es: {
    pinFromExtensions: "Fijar desde Extensiones", installed: "Instalada", ready: "{name} está lista.",
    pinInstruction: "Fíjala desde el menú Extensiones de Chrome y abre {platform}.", open: "Abrir {platform}", readyWhen: "Lista cuando tú quieras",
    privacyDesign: "Privacidad desde el diseño", dataBrowser: "Tus datos permanecen en tu navegador.", seeAccess: "Consulta exactamente a qué accede →",
    independent: "Herramientas independientes para una vida social más tranquila.", support: "Ayuda", privacy: "Privacidad", more: "Más de CleanMySocial",
    explore: "Explorar →", free: "Gratis", anonymousFeedback: "Opinión anónima", extensionUninstalled: "Extensión desinstalada",
    thanksTry: "Antes de irte…", uninstallQuestion: "¿Por qué desinstalaste {name}?", oneAnswer: "Elige un motivo; quizá podamos ayudarte.",
    reinstall: "Reinstalar {name} ↗", whatHappened: "¿Qué ocurrió?", chooseReason: "Elige el motivo más parecido",
    reasonNotWorking: "No funcionó", reasonHard: "Era difícil de usar", reasonMissing: "Faltaba una función", reasonPrivacy: "Privacidad o permisos",
    reasonNoNeed: "Ya no la necesito", reasonOther: "Otro motivo", anythingElse: "¿Algo más?", optional: "Opcional",
    notePlaceholder: "Una nota breve puede ayudarnos a entender el problema.", selectReasonNote: "Elige un motivo para añadir una nota opcional.",
    sending: "Enviando…", sendFeedback: "Enviar opinión", skipFeedback: "Omitir opinión", anonymousNotice: "Anónimo · no incluyas información personal",
    sendError: "No se pudo enviar. Inténtalo de nuevo.", feedbackReceived: "Opinión recibida", feedbackSkipped: "Opinión omitida", thanksHelps: "Gracias, nos ayuda.",
    noProblem: "No pasa nada.", sentAnonymously: "Tu respuesta se envió de forma anónima.", nothingSent: "No se envió ni guardó nada.", exploreAll: "Ver todo →",
  },
  pl: {
    pinFromExtensions: "Przypnij z menu Rozszerzenia", installed: "Zainstalowano", ready: "{name} jest gotowe.",
    pinInstruction: "Przypnij rozszerzenie w menu Chrome, a następnie otwórz {platform}.", open: "Otwórz {platform}", readyWhen: "Gotowe, kiedy Ty jesteś",
    privacyDesign: "Prywatność od podstaw", dataBrowser: "Twoje dane pozostają w przeglądarce.", seeAccess: "Sprawdź dokładnie, do czego ma dostęp →",
    independent: "Niezależne narzędzia dla spokojniejszych mediów społecznościowych.", support: "Pomoc", privacy: "Prywatność", more: "Więcej od CleanMySocial",
    explore: "Zobacz →", free: "Bezpłatne", anonymousFeedback: "Anonimowa opinia", extensionUninstalled: "Rozszerzenie odinstalowane",
    thanksTry: "Zanim odejdziesz…", uninstallQuestion: "Dlaczego odinstalowano {name}?", oneAnswer: "Wybierz jeden powód — być może możemy pomóc.",
    reinstall: "Zainstaluj ponownie {name} ↗", whatHappened: "Co się stało?", chooseReason: "Wybierz najbliższy powód",
    reasonNotWorking: "Nie działało", reasonHard: "Było trudne w użyciu", reasonMissing: "Brakowało funkcji", reasonPrivacy: "Prywatność lub uprawnienia",
    reasonNoNeed: "Już go nie potrzebuję", reasonOther: "Inny powód", anythingElse: "Coś jeszcze?", optional: "Opcjonalnie",
    notePlaceholder: "Krótka notatka pomoże nam zrozumieć problem.", selectReasonNote: "Wybierz powód, aby opcjonalnie dodać notatkę.",
    sending: "Wysyłanie…", sendFeedback: "Wyślij opinię", skipFeedback: "Pomiń opinię", anonymousNotice: "Anonimowo · nie podawaj danych osobowych",
    sendError: "Nie udało się wysłać. Spróbuj ponownie.", feedbackReceived: "Otrzymano opinię", feedbackSkipped: "Pominięto opinię", thanksHelps: "Dziękujemy — to pomaga.",
    noProblem: "Nie ma problemu.", sentAnonymously: "Odpowiedź wysłano anonimowo.", nothingSent: "Nic nie zostało wysłane ani zapisane.", exploreAll: "Zobacz wszystkie →",
  },
  zh_TW: {
    pinFromExtensions: "從擴充功能選單固定", installed: "已安裝", ready: "{name} 已可使用。",
    pinInstruction: "從 Chrome 的擴充功能選單將它固定，然後開啟 {platform}。", open: "開啟 {platform}", readyWhen: "隨時可以開始",
    privacyDesign: "以隱私為核心", dataBrowser: "你的資料只留在瀏覽器中。", seeAccess: "查看它實際存取的內容 →",
    independent: "讓社群生活更安靜的獨立工具。", support: "支援", privacy: "隱私權", more: "更多 CleanMySocial 工具",
    explore: "查看 →", free: "免費", anonymousFeedback: "匿名意見", extensionUninstalled: "擴充功能已解除安裝",
    thanksTry: "在你離開之前…", uninstallQuestion: "你為什麼解除安裝 {name}？", oneAnswer: "選擇一個原因，我們或許能幫上忙。",
    reinstall: "重新安裝 {name} ↗", whatHappened: "發生了什麼事？", chooseReason: "選擇最接近的原因",
    reasonNotWorking: "無法正常運作", reasonHard: "使用起來很困難", reasonMissing: "缺少需要的功能", reasonPrivacy: "隱私權或權限",
    reasonNoNeed: "我不再需要它", reasonOther: "其他原因", anythingElse: "還有其他意見嗎？", optional: "選填",
    notePlaceholder: "簡短說明可以幫助我們了解問題。", selectReasonNote: "選擇原因後可加入選填說明。",
    sending: "傳送中…", sendFeedback: "傳送意見", skipFeedback: "略過意見", anonymousNotice: "匿名 · 請勿填寫個人資料",
    sendError: "無法傳送，請再試一次。", feedbackReceived: "已收到意見", feedbackSkipped: "已略過意見", thanksHelps: "謝謝，這很有幫助。",
    noProblem: "沒問題。", sentAnonymously: "你的回答已匿名傳送。", nothingSent: "沒有傳送或儲存任何內容。", exploreAll: "查看全部 →",
  },
  sv: {
    pinFromExtensions: "Fäst via Tillägg", installed: "Installerat", ready: "{name} är redo.", pinInstruction: "Fäst tillägget via Chromes meny Tillägg och öppna sedan {platform}.",
    open: "Öppna {platform}", readyWhen: "Redo när du är", privacyDesign: "Integritet från början", dataBrowser: "Dina data stannar i webbläsaren.",
    seeAccess: "Se exakt vad tillägget har åtkomst till →", independent: "Oberoende verktyg för ett lugnare socialt liv.", support: "Support", privacy: "Integritet",
    more: "Mer från CleanMySocial", explore: "Utforska →", free: "Gratis", anonymousFeedback: "Anonym feedback", extensionUninstalled: "Tillägget avinstallerat",
    thanksTry: "Innan du går…", uninstallQuestion: "Varför avinstallerade du {name}?", oneAnswer: "Välj en orsak — vi kanske kan hjälpa dig.",
    reinstall: "Installera om {name} ↗", whatHappened: "Vad hände?", chooseReason: "Välj närmaste orsak", reasonNotWorking: "Det fungerade inte",
    reasonHard: "Det var svårt att använda", reasonMissing: "En funktion saknades", reasonPrivacy: "Integritet eller behörigheter", reasonNoNeed: "Jag behöver det inte längre",
    reasonOther: "Något annat", anythingElse: "Något mer?", optional: "Valfritt", notePlaceholder: "En kort anteckning kan hjälpa oss förstå problemet.",
    selectReasonNote: "Välj en orsak för att lägga till en valfri anteckning.", sending: "Skickar…", sendFeedback: "Skicka feedback", skipFeedback: "Hoppa över feedback",
    anonymousNotice: "Anonymt · ta inte med personuppgifter", sendError: "Det gick inte att skicka. Försök igen.", feedbackReceived: "Feedback mottagen",
    feedbackSkipped: "Feedback överhoppad", thanksHelps: "Tack — det hjälper.", noProblem: "Inga problem.", sentAnonymously: "Ditt svar skickades anonymt.",
    nothingSent: "Ingenting skickades eller sparades.", exploreAll: "Utforska alla →",
  },
  da: {
    pinFromExtensions: "Fastgør fra Udvidelser", installed: "Installeret", ready: "{name} er klar.", pinInstruction: "Fastgør udvidelsen fra Chromes menu Udvidelser, og åbn derefter {platform}.",
    open: "Åbn {platform}", readyWhen: "Klar, når du er", privacyDesign: "Privatliv fra starten", dataBrowser: "Dine data bliver i din browser.",
    seeAccess: "Se præcis, hvad den har adgang til →", independent: "Uafhængige værktøjer til et roligere socialt liv.", support: "Support", privacy: "Privatliv",
    more: "Mere fra CleanMySocial", explore: "Udforsk →", free: "Gratis", anonymousFeedback: "Anonym feedback", extensionUninstalled: "Udvidelsen er afinstalleret",
    thanksTry: "Før du går…", uninstallQuestion: "Hvorfor afinstallerede du {name}?", oneAnswer: "Vælg én årsag — måske kan vi hjælpe.",
    reinstall: "Geninstaller {name} ↗", whatHappened: "Hvad skete der?", chooseReason: "Vælg den nærmeste årsag", reasonNotWorking: "Den virkede ikke",
    reasonHard: "Den var svær at bruge", reasonMissing: "En funktion manglede", reasonPrivacy: "Privatliv eller tilladelser", reasonNoNeed: "Jeg har ikke længere brug for den",
    reasonOther: "Noget andet", anythingElse: "Er der andet?", optional: "Valgfrit", notePlaceholder: "En kort note kan hjælpe os med at forstå problemet.",
    selectReasonNote: "Vælg en årsag for at tilføje en valgfri note.", sending: "Sender…", sendFeedback: "Send feedback", skipFeedback: "Spring feedback over",
    anonymousNotice: "Anonymt · medtag ikke personlige oplysninger", sendError: "Kunne ikke sende. Prøv igen.", feedbackReceived: "Feedback modtaget",
    feedbackSkipped: "Feedback sprunget over", thanksHelps: "Tak — det hjælper.", noProblem: "Intet problem.", sentAnonymously: "Dit svar blev sendt anonymt.",
    nothingSent: "Intet blev sendt eller gemt.", exploreAll: "Udforsk alle →",
  },
  no: {
    pinFromExtensions: "Fest fra Utvidelser", installed: "Installert", ready: "{name} er klar.", pinInstruction: "Fest utvidelsen fra Chrome-menyen Utvidelser, og åpne deretter {platform}.",
    open: "Åpne {platform}", readyWhen: "Klar når du er", privacyDesign: "Personvern fra starten", dataBrowser: "Dataene dine forblir i nettleseren.",
    seeAccess: "Se nøyaktig hva den har tilgang til →", independent: "Uavhengige verktøy for et roligere sosialt liv.", support: "Brukerstøtte", privacy: "Personvern",
    more: "Mer fra CleanMySocial", explore: "Utforsk →", free: "Gratis", anonymousFeedback: "Anonym tilbakemelding", extensionUninstalled: "Utvidelsen er avinstallert",
    thanksTry: "Før du går…", uninstallQuestion: "Hvorfor avinstallerte du {name}?", oneAnswer: "Velg én årsak — kanskje vi kan hjelpe.",
    reinstall: "Installer {name} på nytt ↗", whatHappened: "Hva skjedde?", chooseReason: "Velg årsaken som passer best", reasonNotWorking: "Den fungerte ikke",
    reasonHard: "Den var vanskelig å bruke", reasonMissing: "En funksjon manglet", reasonPrivacy: "Personvern eller tillatelser", reasonNoNeed: "Jeg trenger den ikke lenger",
    reasonOther: "Noe annet", anythingElse: "Noe mer?", optional: "Valgfritt", notePlaceholder: "En kort kommentar kan hjelpe oss å forstå problemet.",
    selectReasonNote: "Velg en årsak for å legge til en valgfri kommentar.", sending: "Sender…", sendFeedback: "Send tilbakemelding", skipFeedback: "Hopp over tilbakemelding",
    anonymousNotice: "Anonymt · ikke ta med personopplysninger", sendError: "Kunne ikke sende. Prøv igjen.", feedbackReceived: "Tilbakemelding mottatt",
    feedbackSkipped: "Tilbakemelding hoppet over", thanksHelps: "Takk — det hjelper.", noProblem: "Ikke noe problem.", sentAnonymously: "Svaret ditt ble sendt anonymt.",
    nothingSent: "Ingenting ble sendt eller lagret.", exploreAll: "Utforsk alle →",
  },
  fi: {
    pinFromExtensions: "Kiinnitä Laajennukset-valikosta", installed: "Asennettu", ready: "{name} on valmis.", pinInstruction: "Kiinnitä laajennus Chromen Laajennukset-valikosta ja avaa sitten {platform}.",
    open: "Avaa {platform}", readyWhen: "Valmis kun sinäkin", privacyDesign: "Tietosuoja suunnittelun lähtökohtana", dataBrowser: "Tietosi pysyvät selaimessasi.",
    seeAccess: "Katso tarkasti, mihin sillä on pääsy →", independent: "Riippumattomia työkaluja rauhallisempaan some-elämään.", support: "Tuki", privacy: "Tietosuoja",
    more: "Lisää CleanMySocialilta", explore: "Tutustu →", free: "Ilmainen", anonymousFeedback: "Anonyymi palaute", extensionUninstalled: "Laajennus poistettu",
    thanksTry: "Ennen kuin lähdet…", uninstallQuestion: "Miksi poistit laajennuksen {name}?", oneAnswer: "Valitse yksi syy — voimme ehkä auttaa.",
    reinstall: "Asenna {name} uudelleen ↗", whatHappened: "Mitä tapahtui?", chooseReason: "Valitse lähin syy", reasonNotWorking: "Se ei toiminut",
    reasonHard: "Sitä oli vaikea käyttää", reasonMissing: "Ominaisuus puuttui", reasonPrivacy: "Tietosuoja tai käyttöoikeudet", reasonNoNeed: "En tarvitse sitä enää",
    reasonOther: "Jokin muu", anythingElse: "Jotain muuta?", optional: "Valinnainen", notePlaceholder: "Lyhyt huomautus voi auttaa meitä ymmärtämään ongelmaa.",
    selectReasonNote: "Valitse syy lisätäksesi valinnaisen huomautuksen.", sending: "Lähetetään…", sendFeedback: "Lähetä palaute", skipFeedback: "Ohita palaute",
    anonymousNotice: "Anonyymi · älä lisää henkilötietoja", sendError: "Lähetys epäonnistui. Yritä uudelleen.", feedbackReceived: "Palaute vastaanotettu",
    feedbackSkipped: "Palaute ohitettu", thanksHelps: "Kiitos — siitä on apua.", noProblem: "Ei hätää.", sentAnonymously: "Vastauksesi lähetettiin anonyymisti.",
    nothingSent: "Mitään ei lähetetty eikä tallennettu.", exploreAll: "Tutustu kaikkiin →",
  },
  he: {
    pinFromExtensions: "הצמדה מתפריט התוספים", installed: "הותקן", ready: "{name} מוכן לשימוש.", pinInstruction: "יש להצמיד מתפריט התוספים של Chrome ואז לפתוח את {platform}.",
    open: "פתיחת {platform}", readyWhen: "מוכן כשנוח לך", privacyDesign: "פרטיות כבר מהתכנון", dataBrowser: "הנתונים שלך נשארים בדפדפן.",
    seeAccess: "לראות בדיוק למה יש גישה →", independent: "כלים עצמאיים לחיים שקטים יותר ברשתות החברתיות.", support: "תמיכה", privacy: "פרטיות",
    more: "עוד מ־CleanMySocial", explore: "לגלות →", free: "חינם", anonymousFeedback: "משוב אנונימי", extensionUninstalled: "התוסף הוסר",
    thanksTry: "לפני שממשיכים…", uninstallQuestion: "למה הסרת את {name}?", oneAnswer: "בחרו סיבה אחת — אולי נוכל לעזור.", reinstall: "התקנה מחדש של {name} ↗",
    whatHappened: "מה קרה?", chooseReason: "בחרו את הסיבה הקרובה ביותר", reasonNotWorking: "זה לא עבד", reasonHard: "היה קשה להשתמש בו",
    reasonMissing: "חסרה תכונה", reasonPrivacy: "פרטיות או הרשאות", reasonNoNeed: "כבר אין לי צורך בו", reasonOther: "סיבה אחרת",
    anythingElse: "עוד משהו?", optional: "רשות", notePlaceholder: "הערה קצרה יכולה לעזור לנו להבין את הבעיה.", selectReasonNote: "בחרו סיבה כדי להוסיף הערה אופציונלית.",
    sending: "שולח…", sendFeedback: "שליחת משוב", skipFeedback: "דילוג על משוב", anonymousNotice: "אנונימי · אין לכלול מידע אישי",
    sendError: "לא ניתן לשלוח. נסו שוב.", feedbackReceived: "המשוב התקבל", feedbackSkipped: "המשוב דולג", thanksHelps: "תודה — זה עוזר.",
    noProblem: "אין בעיה.", sentAnonymously: "התשובה נשלחה באופן אנונימי.", nothingSent: "דבר לא נשלח או נשמר.", exploreAll: "לכל הכלים →",
  },
  cs: {
    pinFromExtensions: "Připnout z nabídky Rozšíření", installed: "Nainstalováno", ready: "{name} je připraveno.", pinInstruction: "Připněte rozšíření z nabídky Chrome a poté otevřete {platform}.",
    open: "Otevřít {platform}", readyWhen: "Připraveno, až budete", privacyDesign: "Soukromí od návrhu", dataBrowser: "Vaše data zůstávají v prohlížeči.",
    seeAccess: "Podívejte se přesně, k čemu má přístup →", independent: "Nezávislé nástroje pro klidnější život na sociálních sítích.", support: "Podpora", privacy: "Soukromí",
    more: "Více od CleanMySocial", explore: "Prozkoumat →", free: "Zdarma", anonymousFeedback: "Anonymní zpětná vazba", extensionUninstalled: "Rozšíření odinstalováno",
    thanksTry: "Než odejdete…", uninstallQuestion: "Proč jste odinstalovali {name}?", oneAnswer: "Vyberte jeden důvod — možná vám můžeme pomoci.",
    reinstall: "Znovu nainstalovat {name} ↗", whatHappened: "Co se stalo?", chooseReason: "Vyberte nejbližší důvod", reasonNotWorking: "Nefungovalo",
    reasonHard: "Bylo obtížné ho používat", reasonMissing: "Chyběla funkce", reasonPrivacy: "Soukromí nebo oprávnění", reasonNoNeed: "Už ho nepotřebuji",
    reasonOther: "Něco jiného", anythingElse: "Ještě něco?", optional: "Volitelné", notePlaceholder: "Krátká poznámka nám může pomoci pochopit problém.",
    selectReasonNote: "Vyberte důvod a případně přidejte poznámku.", sending: "Odesílání…", sendFeedback: "Odeslat zpětnou vazbu", skipFeedback: "Přeskočit zpětnou vazbu",
    anonymousNotice: "Anonymní · neuvádějte osobní údaje", sendError: "Odeslání se nezdařilo. Zkuste to znovu.", feedbackReceived: "Zpětná vazba přijata",
    feedbackSkipped: "Zpětná vazba přeskočena", thanksHelps: "Děkujeme — pomáhá to.", noProblem: "Žádný problém.", sentAnonymously: "Vaše odpověď byla odeslána anonymně.",
    nothingSent: "Nic nebylo odesláno ani uloženo.", exploreAll: "Prozkoumat vše →",
  },
  pt_PT: {
    pinFromExtensions: "Afixar a partir das Extensões", installed: "Instalada", ready: "{name} está pronta.", pinInstruction: "Afixe-a a partir do menu Extensões do Chrome e depois abra {platform}.",
    open: "Abrir {platform}", readyWhen: "Pronta quando quiser", privacyDesign: "Privacidade desde a conceção", dataBrowser: "Os seus dados ficam no navegador.",
    seeAccess: "Veja exatamente a que acede →", independent: "Ferramentas independentes para uma vida social mais tranquila.", support: "Apoio", privacy: "Privacidade",
    more: "Mais da CleanMySocial", explore: "Explorar →", free: "Grátis", anonymousFeedback: "Opinião anónima", extensionUninstalled: "Extensão desinstalada",
    thanksTry: "Antes de sair…", uninstallQuestion: "Porque desinstalou {name}?", oneAnswer: "Escolha um motivo — talvez possamos ajudar.", reinstall: "Reinstalar {name} ↗",
    whatHappened: "O que aconteceu?", chooseReason: "Escolha o motivo mais próximo", reasonNotWorking: "Não funcionou", reasonHard: "Era difícil de utilizar",
    reasonMissing: "Faltava uma funcionalidade", reasonPrivacy: "Privacidade ou permissões", reasonNoNeed: "Já não preciso dela", reasonOther: "Outro motivo",
    anythingElse: "Mais alguma coisa?", optional: "Opcional", notePlaceholder: "Uma nota curta pode ajudar-nos a compreender o problema.",
    selectReasonNote: "Escolha um motivo para adicionar uma nota opcional.", sending: "A enviar…", sendFeedback: "Enviar opinião", skipFeedback: "Ignorar opinião",
    anonymousNotice: "Anónimo · não inclua informações pessoais", sendError: "Não foi possível enviar. Tente novamente.", feedbackReceived: "Opinião recebida",
    feedbackSkipped: "Opinião ignorada", thanksHelps: "Obrigado — isso ajuda.", noProblem: "Sem problema.", sentAnonymously: "A sua resposta foi enviada anonimamente.",
    nothingSent: "Nada foi enviado nem guardado.", exploreAll: "Explorar tudo →",
  },
  pt_BR: {
    pinFromExtensions: "Fixar pelas Extensões", installed: "Instalada", ready: "{name} está pronta.", pinInstruction: "Fixe-a pelo menu Extensões do Chrome e depois abra {platform}.",
    open: "Abrir {platform}", readyWhen: "Pronta quando você estiver", privacyDesign: "Privacidade desde o início", dataBrowser: "Seus dados permanecem no seu navegador.",
    seeAccess: "Veja exatamente o que ela acessa →", independent: "Ferramentas independentes para uma vida social mais tranquila.", support: "Suporte", privacy: "Privacidade",
    more: "Mais da CleanMySocial", explore: "Explorar →", free: "Grátis", anonymousFeedback: "Feedback anônimo", extensionUninstalled: "Extensão desinstalada",
    thanksTry: "Antes de ir…", uninstallQuestion: "Por que você desinstalou {name}?", oneAnswer: "Escolha um motivo — talvez possamos ajudar.", reinstall: "Reinstalar {name} ↗",
    whatHappened: "O que aconteceu?", chooseReason: "Escolha o motivo mais próximo", reasonNotWorking: "Não funcionou", reasonHard: "Era difícil de usar",
    reasonMissing: "Faltava um recurso", reasonPrivacy: "Privacidade ou permissões", reasonNoNeed: "Não preciso mais dela", reasonOther: "Outro motivo",
    anythingElse: "Mais alguma coisa?", optional: "Opcional", notePlaceholder: "Uma observação curta pode nos ajudar a entender o problema.", selectReasonNote: "Escolha um motivo para adicionar uma observação opcional.",
    sending: "Enviando…", sendFeedback: "Enviar feedback", skipFeedback: "Pular feedback", anonymousNotice: "Anônimo · não inclua informações pessoais",
    sendError: "Não foi possível enviar. Tente novamente.", feedbackReceived: "Feedback recebido", feedbackSkipped: "Feedback ignorado", thanksHelps: "Obrigado — isso ajuda.",
    noProblem: "Sem problema.", sentAnonymously: "Sua resposta foi enviada anonimamente.", nothingSent: "Nada foi enviado ou armazenado.", exploreAll: "Explorar tudo →",
  },
  es_419: {
    pinFromExtensions: "Fijar desde Extensiones", installed: "Instalada", ready: "{name} está lista.", pinInstruction: "Fíjala desde el menú Extensiones de Chrome y luego abre {platform}.",
    open: "Abrir {platform}", readyWhen: "Lista cuando tú quieras", privacyDesign: "Privacidad desde el diseño", dataBrowser: "Tus datos permanecen en tu navegador.",
    seeAccess: "Consulta exactamente a qué accede →", independent: "Herramientas independientes para una vida digital más tranquila.", support: "Ayuda", privacy: "Privacidad",
    more: "Más de CleanMySocial", explore: "Explorar →", free: "Gratis", anonymousFeedback: "Opinión anónima", extensionUninstalled: "Extensión desinstalada",
    thanksTry: "Antes de irte…", uninstallQuestion: "¿Por qué desinstalaste {name}?", oneAnswer: "Elige un motivo; quizá podamos ayudarte.", reinstall: "Reinstalar {name} ↗",
    whatHappened: "¿Qué pasó?", chooseReason: "Elige el motivo más cercano", reasonNotWorking: "No funcionó", reasonHard: "Era difícil de usar",
    reasonMissing: "Faltaba una función", reasonPrivacy: "Privacidad o permisos", reasonNoNeed: "Ya no la necesito", reasonOther: "Otro motivo",
    anythingElse: "¿Algo más?", optional: "Opcional", notePlaceholder: "Una nota breve puede ayudarnos a entender el problema.", selectReasonNote: "Elige un motivo para agregar una nota opcional.",
    sending: "Enviando…", sendFeedback: "Enviar opinión", skipFeedback: "Omitir opinión", anonymousNotice: "Anónimo · no incluyas información personal",
    sendError: "No se pudo enviar. Inténtalo de nuevo.", feedbackReceived: "Opinión recibida", feedbackSkipped: "Opinión omitida", thanksHelps: "Gracias, nos ayuda.",
    noProblem: "No hay problema.", sentAnonymously: "Tu respuesta se envió de forma anónima.", nothingSent: "No se envió ni guardó nada.", exploreAll: "Ver todo →",
  },
  ar: {
    pinFromExtensions: "ثبّت من قائمة الإضافات", installed: "تم التثبيت", ready: "{name} جاهز للاستخدام.", pinInstruction: "ثبّته من قائمة إضافات Chrome، ثم افتح {platform}.",
    open: "فتح {platform}", readyWhen: "جاهز عندما تكون مستعدًا", privacyDesign: "الخصوصية في صميم التصميم", dataBrowser: "تبقى بياناتك في متصفحك.",
    seeAccess: "اطّلع بالتحديد على ما يمكنه الوصول إليه ←", independent: "أدوات مستقلة لتجربة أكثر هدوءًا على الشبكات الاجتماعية.", support: "الدعم", privacy: "الخصوصية",
    more: "المزيد من CleanMySocial", explore: "استكشف ←", free: "مجاني", anonymousFeedback: "ملاحظات مجهولة", extensionUninstalled: "تمت إزالة الإضافة",
    thanksTry: "قبل أن تغادر…", uninstallQuestion: "لماذا أزلت {name}؟", oneAnswer: "اختر سببًا واحدًا — قد نتمكن من مساعدتك.", reinstall: "إعادة تثبيت {name} ↗",
    whatHappened: "ماذا حدث؟", chooseReason: "اختر السبب الأقرب", reasonNotWorking: "لم تعمل", reasonHard: "كان استخدامها صعبًا",
    reasonMissing: "ميزة مطلوبة غير موجودة", reasonPrivacy: "الخصوصية أو الأذونات", reasonNoNeed: "لم أعد بحاجة إليها", reasonOther: "سبب آخر",
    anythingElse: "هل لديك ملاحظة أخرى؟", optional: "اختياري", notePlaceholder: "قد تساعدنا ملاحظة قصيرة على فهم المشكلة.", selectReasonNote: "اختر سببًا لإضافة ملاحظة اختيارية.",
    sending: "جارٍ الإرسال…", sendFeedback: "إرسال الملاحظات", skipFeedback: "تخطي الملاحظات", anonymousNotice: "مجهول · يُرجى عدم تضمين معلومات شخصية",
    sendError: "تعذر الإرسال. حاول مرة أخرى.", feedbackReceived: "تم استلام الملاحظات", feedbackSkipped: "تم تخطي الملاحظات", thanksHelps: "شكرًا — هذا مفيد.",
    noProblem: "لا مشكلة.", sentAnonymously: "تم إرسال إجابتك بشكل مجهول.", nothingSent: "لم يتم إرسال أو تخزين أي شيء.", exploreAll: "استكشف الكل ←",
  },
  ro: {
    pinFromExtensions: "Fixează din Extensii", installed: "Instalată", ready: "{name} este gata.", pinInstruction: "Fixează extensia din meniul Extensii Chrome, apoi deschide {platform}.",
    open: "Deschide {platform}", readyWhen: "Gata când ești și tu", privacyDesign: "Confidențialitate din proiectare", dataBrowser: "Datele tale rămân în browser.",
    seeAccess: "Vezi exact la ce are acces →", independent: "Instrumente independente pentru o viață socială mai liniștită.", support: "Asistență", privacy: "Confidențialitate",
    more: "Mai multe de la CleanMySocial", explore: "Explorează →", free: "Gratuit", anonymousFeedback: "Feedback anonim", extensionUninstalled: "Extensie dezinstalată",
    thanksTry: "Înainte să pleci…", uninstallQuestion: "De ce ai dezinstalat {name}?", oneAnswer: "Alege un motiv — poate te putem ajuta.", reinstall: "Reinstalează {name} ↗",
    whatHappened: "Ce s-a întâmplat?", chooseReason: "Alege motivul cel mai apropiat", reasonNotWorking: "Nu a funcționat", reasonHard: "A fost dificil de folosit",
    reasonMissing: "Lipsea o funcție", reasonPrivacy: "Confidențialitate sau permisiuni", reasonNoNeed: "Nu mai am nevoie de ea", reasonOther: "Alt motiv",
    anythingElse: "Mai dorești să adaugi ceva?", optional: "Opțional", notePlaceholder: "O notă scurtă ne poate ajuta să înțelegem problema.", selectReasonNote: "Alege un motiv pentru a adăuga o notă opțională.",
    sending: "Se trimite…", sendFeedback: "Trimite feedback", skipFeedback: "Omite feedbackul", anonymousNotice: "Anonim · nu include informații personale",
    sendError: "Nu s-a putut trimite. Încearcă din nou.", feedbackReceived: "Feedback primit", feedbackSkipped: "Feedback omis", thanksHelps: "Mulțumim — ne ajută.",
    noProblem: "Nicio problemă.", sentAnonymously: "Răspunsul tău a fost trimis anonim.", nothingSent: "Nu a fost trimis sau stocat nimic.", exploreAll: "Explorează tot →",
  },
  hu: {
    pinFromExtensions: "Rögzítés a Bővítményekből", installed: "Telepítve", ready: "A(z) {name} használatra kész.", pinInstruction: "Rögzítsd a Chrome Bővítmények menüjéből, majd nyisd meg: {platform}.",
    open: "{platform} megnyitása", readyWhen: "Készen áll, amikor te is", privacyDesign: "Beépített adatvédelem", dataBrowser: "Az adataid a böngésződben maradnak.",
    seeAccess: "Nézd meg pontosan, mihez fér hozzá →", independent: "Független eszközök a nyugodtabb közösségi élethez.", support: "Támogatás", privacy: "Adatvédelem",
    more: "Továbbiak a CleanMySocialtól", explore: "Felfedezés →", free: "Ingyenes", anonymousFeedback: "Névtelen visszajelzés", extensionUninstalled: "Bővítmény eltávolítva",
    thanksTry: "Mielőtt elmész…", uninstallQuestion: "Miért távolítottad el ezt: {name}?", oneAnswer: "Válassz egy okot — talán tudunk segíteni.", reinstall: "{name} újratelepítése ↗",
    whatHappened: "Mi történt?", chooseReason: "Válaszd ki a leginkább megfelelő okot", reasonNotWorking: "Nem működött", reasonHard: "Nehéz volt használni",
    reasonMissing: "Hiányzott egy funkció", reasonPrivacy: "Adatvédelem vagy engedélyek", reasonNoNeed: "Már nincs rá szükségem", reasonOther: "Más ok",
    anythingElse: "Van még valami?", optional: "Nem kötelező", notePlaceholder: "Egy rövid megjegyzés segíthet megérteni a problémát.", selectReasonNote: "Válassz egy okot, és adj hozzá egy nem kötelező megjegyzést.",
    sending: "Küldés…", sendFeedback: "Visszajelzés küldése", skipFeedback: "Visszajelzés kihagyása", anonymousNotice: "Névtelen · ne adj meg személyes adatokat",
    sendError: "Nem sikerült elküldeni. Próbáld újra.", feedbackReceived: "Visszajelzés megérkezett", feedbackSkipped: "Visszajelzés kihagyva", thanksHelps: "Köszönjük — ez segít.",
    noProblem: "Semmi gond.", sentAnonymously: "A válaszod névtelenül lett elküldve.", nothingSent: "Semmit nem küldtünk el és nem tároltunk.", exploreAll: "Összes felfedezése →",
  },
  zh_CN: {
    pinFromExtensions: "从扩展程序中固定", installed: "已安装", ready: "{name} 已可使用。", pinInstruction: "在 Chrome 的扩展程序菜单中固定它，然后打开 {platform}。",
    open: "打开 {platform}", readyWhen: "你准备好了就能开始", privacyDesign: "隐私是设计的一部分", dataBrowser: "你的数据留在浏览器里。",
    seeAccess: "查看它具体能访问什么 →", independent: "让社交更清净的独立工具。", support: "支持", privacy: "隐私",
    more: "更多来自 CleanMySocial", explore: "去看看 →", free: "免费", anonymousFeedback: "匿名反馈", extensionUninstalled: "扩展已卸载",
    thanksTry: "在你离开之前…", uninstallQuestion: "你为什么卸载了 {name}？", oneAnswer: "选择一个原因，我们也许能帮上忙。", reinstall: "重新安装 {name} ↗",
    whatHappened: "发生了什么？", chooseReason: "选择最接近的原因", reasonNotWorking: "无法正常工作", reasonHard: "使用起来太麻烦",
    reasonMissing: "缺少某个功能", reasonPrivacy: "隐私或权限问题", reasonNoNeed: "我不再需要了", reasonOther: "其他原因",
    anythingElse: "还有别的吗？", optional: "可选", notePlaceholder: "简短的说明能帮助我们理解问题。", selectReasonNote: "选择一个原因，并可补充说明。",
    sending: "发送中…", sendFeedback: "发送反馈", skipFeedback: "跳过反馈", anonymousNotice: "匿名 · 请勿填写个人信息",
    sendError: "发送失败，请重试。", feedbackReceived: "已收到反馈", feedbackSkipped: "已跳过反馈", thanksHelps: "谢谢 — 这很有帮助。",
    noProblem: "没关系。", sentAnonymously: "你的回答已匿名发送。", nothingSent: "我们没有发送也没有存储任何内容。", exploreAll: "查看全部 →",
  },
  tr: {
    pinFromExtensions: "Uzantılardan sabitle", installed: "Yüklendi", ready: "{name} hazır.", pinInstruction: "Chrome’un Uzantılar menüsünden sabitleyin, ardından {platform} platformunu açın.",
    open: "{platform} platformunu aç", readyWhen: "Hazır olduğunuzda başlayın", privacyDesign: "Gizlilik odaklı tasarım", dataBrowser: "Verileriniz tarayıcınızda kalır.",
    seeAccess: "Tam olarak nelere eriştiğini görün →", independent: "Daha sakin bir sosyal yaşam için bağımsız araçlar.", support: "Destek", privacy: "Gizlilik",
    more: "CleanMySocial’dan daha fazlası", explore: "Keşfet →", free: "Ücretsiz", anonymousFeedback: "Anonim geri bildirim", extensionUninstalled: "Uzantı kaldırıldı",
    thanksTry: "Gitmeden önce…", uninstallQuestion: "{name} uzantısını neden kaldırdınız?", oneAnswer: "Bir neden seçin — size yardımcı olabiliriz.", reinstall: "{name} uzantısını yeniden yükle ↗",
    whatHappened: "Ne oldu?", chooseReason: "En yakın nedeni seçin", reasonNotWorking: "Çalışmadı", reasonHard: "Kullanımı zordu",
    reasonMissing: "Bir özellik eksikti", reasonPrivacy: "Gizlilik veya izinler", reasonNoNeed: "Artık ihtiyacım yok", reasonOther: "Başka bir neden",
    anythingElse: "Eklemek istediğiniz bir şey var mı?", optional: "İsteğe bağlı", notePlaceholder: "Kısa bir not sorunu anlamamıza yardımcı olabilir.", selectReasonNote: "İsteğe bağlı bir not eklemek için bir neden seçin.",
    sending: "Gönderiliyor…", sendFeedback: "Geri bildirim gönder", skipFeedback: "Geri bildirimi atla", anonymousNotice: "Anonim · lütfen kişisel bilgi eklemeyin",
    sendError: "Gönderilemedi. Lütfen tekrar deneyin.", feedbackReceived: "Geri bildirim alındı", feedbackSkipped: "Geri bildirim atlandı", thanksHelps: "Teşekkürler — bu yardımcı oldu.",
    noProblem: "Sorun değil.", sentAnonymously: "Yanıtınız anonim olarak gönderildi.", nothingSent: "Hiçbir şey gönderilmedi veya kaydedilmedi.", exploreAll: "Tümünü keşfet →",
  },
  th: {
    pinFromExtensions: "ปักหมุดจากส่วนขยาย", installed: "ติดตั้งแล้ว", ready: "{name} พร้อมใช้งานแล้ว", pinInstruction: "ปักหมุดจากเมนูส่วนขยายของ Chrome แล้วเปิด {platform}",
    open: "เปิด {platform}", readyWhen: "พร้อมเมื่อคุณพร้อม", privacyDesign: "ออกแบบโดยคำนึงถึงความเป็นส่วนตัว", dataBrowser: "ข้อมูลของคุณจะอยู่ในเบราว์เซอร์เท่านั้น",
    seeAccess: "ดูว่าเข้าถึงอะไรได้บ้าง →", independent: "เครื่องมืออิสระเพื่อชีวิตโซเชียลที่สงบขึ้น", support: "ฝ่ายช่วยเหลือ", privacy: "ความเป็นส่วนตัว",
    more: "เพิ่มเติมจาก CleanMySocial", explore: "สำรวจ →", free: "ฟรี", anonymousFeedback: "ความคิดเห็นแบบไม่ระบุตัวตน", extensionUninstalled: "ถอนการติดตั้งส่วนขยายแล้ว",
    thanksTry: "ก่อนที่คุณจะไป…", uninstallQuestion: "เหตุใดคุณจึงถอนการติดตั้ง {name}?", oneAnswer: "เลือกหนึ่งเหตุผล — เราอาจช่วยคุณได้", reinstall: "ติดตั้ง {name} อีกครั้ง ↗",
    whatHappened: "เกิดอะไรขึ้น?", chooseReason: "เลือกเหตุผลที่ใกล้เคียงที่สุด", reasonNotWorking: "ใช้งานไม่ได้", reasonHard: "ใช้งานยาก",
    reasonMissing: "ขาดฟีเจอร์ที่ต้องการ", reasonPrivacy: "ความเป็นส่วนตัวหรือสิทธิ์", reasonNoNeed: "ฉันไม่ต้องการใช้อีกแล้ว", reasonOther: "เหตุผลอื่น",
    anythingElse: "มีอะไรเพิ่มเติมไหม?", optional: "ไม่บังคับ", notePlaceholder: "ข้อความสั้น ๆ ช่วยให้เราเข้าใจปัญหาได้", selectReasonNote: "เลือกเหตุผลเพื่อเพิ่มข้อความเพิ่มเติมได้",
    sending: "กำลังส่ง…", sendFeedback: "ส่งความคิดเห็น", skipFeedback: "ข้ามความคิดเห็น", anonymousNotice: "ไม่ระบุตัวตน · โปรดอย่าใส่ข้อมูลส่วนบุคคล",
    sendError: "ส่งไม่ได้ โปรดลองอีกครั้ง", feedbackReceived: "ได้รับความคิดเห็นแล้ว", feedbackSkipped: "ข้ามความคิดเห็นแล้ว", thanksHelps: "ขอบคุณ ข้อมูลนี้ช่วยเราได้",
    noProblem: "ไม่มีปัญหา", sentAnonymously: "คำตอบของคุณถูกส่งแบบไม่ระบุตัวตนแล้ว", nothingSent: "ไม่มีการส่งหรือจัดเก็บข้อมูลใด ๆ", exploreAll: "ดูทั้งหมด →",
  },
  id: {
    pinFromExtensions: "Sematkan dari Ekstensi", installed: "Terpasang", ready: "{name} siap digunakan.", pinInstruction: "Sematkan dari menu Ekstensi Chrome, lalu buka {platform}.",
    open: "Buka {platform}", readyWhen: "Siap saat Anda siap", privacyDesign: "Privasi sejak awal", dataBrowser: "Data Anda tetap berada di browser.",
    seeAccess: "Lihat persis apa yang dapat diakses →", independent: "Alat independen untuk kehidupan sosial yang lebih tenang.", support: "Dukungan", privacy: "Privasi",
    more: "Lainnya dari CleanMySocial", explore: "Jelajahi →", free: "Gratis", anonymousFeedback: "Masukan anonim", extensionUninstalled: "Ekstensi dihapus",
    thanksTry: "Sebelum Anda pergi…", uninstallQuestion: "Mengapa Anda menghapus {name}?", oneAnswer: "Pilih satu alasan — mungkin kami dapat membantu.", reinstall: "Pasang ulang {name} ↗",
    whatHappened: "Apa yang terjadi?", chooseReason: "Pilih alasan yang paling sesuai", reasonNotWorking: "Tidak berfungsi", reasonHard: "Sulit digunakan",
    reasonMissing: "Ada fitur yang kurang", reasonPrivacy: "Privasi atau izin", reasonNoNeed: "Saya tidak membutuhkannya lagi", reasonOther: "Alasan lain",
    anythingElse: "Ada tambahan?", optional: "Opsional", notePlaceholder: "Catatan singkat dapat membantu kami memahami masalahnya.", selectReasonNote: "Pilih alasan untuk menambahkan catatan opsional.",
    sending: "Mengirim…", sendFeedback: "Kirim masukan", skipFeedback: "Lewati masukan", anonymousNotice: "Anonim · jangan sertakan informasi pribadi",
    sendError: "Tidak dapat mengirim. Silakan coba lagi.", feedbackReceived: "Masukan diterima", feedbackSkipped: "Masukan dilewati", thanksHelps: "Terima kasih — ini membantu.",
    noProblem: "Tidak masalah.", sentAnonymously: "Jawaban Anda dikirim secara anonim.", nothingSent: "Tidak ada yang dikirim atau disimpan.", exploreAll: "Jelajahi semua →",
  },
  vi: {
    pinFromExtensions: "Ghim từ Tiện ích", installed: "Đã cài đặt", ready: "{name} đã sẵn sàng.", pinInstruction: "Ghim tiện ích từ menu Tiện ích của Chrome, sau đó mở {platform}.",
    open: "Mở {platform}", readyWhen: "Sẵn sàng khi bạn sẵn sàng", privacyDesign: "Thiết kế ưu tiên quyền riêng tư", dataBrowser: "Dữ liệu của bạn chỉ ở trong trình duyệt.",
    seeAccess: "Xem chính xác tiện ích truy cập gì →", independent: "Công cụ độc lập cho đời sống mạng xã hội yên tĩnh hơn.", support: "Hỗ trợ", privacy: "Quyền riêng tư",
    more: "Thêm từ CleanMySocial", explore: "Khám phá →", free: "Miễn phí", anonymousFeedback: "Phản hồi ẩn danh", extensionUninstalled: "Đã gỡ tiện ích",
    thanksTry: "Trước khi bạn rời đi…", uninstallQuestion: "Vì sao bạn gỡ {name}?", oneAnswer: "Chọn một lý do — chúng tôi có thể giúp bạn.", reinstall: "Cài đặt lại {name} ↗",
    whatHappened: "Điều gì đã xảy ra?", chooseReason: "Chọn lý do phù hợp nhất", reasonNotWorking: "Không hoạt động", reasonHard: "Khó sử dụng",
    reasonMissing: "Thiếu một tính năng", reasonPrivacy: "Quyền riêng tư hoặc quyền truy cập", reasonNoNeed: "Tôi không cần nữa", reasonOther: "Lý do khác",
    anythingElse: "Bạn muốn bổ sung gì không?", optional: "Không bắt buộc", notePlaceholder: "Một ghi chú ngắn có thể giúp chúng tôi hiểu vấn đề.", selectReasonNote: "Chọn lý do để thêm ghi chú không bắt buộc.",
    sending: "Đang gửi…", sendFeedback: "Gửi phản hồi", skipFeedback: "Bỏ qua phản hồi", anonymousNotice: "Ẩn danh · vui lòng không cung cấp thông tin cá nhân",
    sendError: "Không thể gửi. Vui lòng thử lại.", feedbackReceived: "Đã nhận phản hồi", feedbackSkipped: "Đã bỏ qua phản hồi", thanksHelps: "Cảm ơn — thông tin này rất hữu ích.",
    noProblem: "Không sao.", sentAnonymously: "Câu trả lời của bạn đã được gửi ẩn danh.", nothingSent: "Không có gì được gửi hoặc lưu.", exploreAll: "Khám phá tất cả →",
  },
  el: {
    pinFromExtensions: "Καρφίτσωμα από τις Επεκτάσεις",
    installed: "Εγκαταστάθηκε",
    ready: "Το {name} είναι έτοιμο.",
    pinInstruction: "Καρφιτσώστε το από το μενού Επεκτάσεις του Chrome και μετά ανοίξτε το {platform}.",
    open: "Άνοιγμα {platform}",
    readyWhen: "Έτοιμο όποτε θέλετε",
    privacyDesign: "Απόρρητο από τον σχεδιασμό",
    dataBrowser: "Τα δεδομένα σας μένουν στο πρόγραμμα περιήγησης.",
    seeAccess: "Δείτε ακριβώς σε τι έχει πρόσβαση →",
    independent: "Ανεξάρτητα εργαλεία για πιο ήρεμη ζωή στα social media.",
    support: "Υποστήριξη",
    privacy: "Απόρρητο",
    more: "Περισσότερα από το CleanMySocial",
    explore: "Εξερεύνηση →",
    free: "Δωρεάν",
    anonymousFeedback: "Ανώνυμα σχόλια",
    extensionUninstalled: "Η επέκταση απεγκαταστάθηκε",
    thanksTry: "Πριν φύγετε…",
    uninstallQuestion: "Γιατί απεγκαταστήσατε το {name};",
    oneAnswer: "Επιλέξτε έναν λόγο — ίσως μπορούμε να βοηθήσουμε.",
    reinstall: "Επανεγκατάσταση {name} ↗",
    whatHappened: "Τι συνέβη;",
    chooseReason: "Επιλέξτε τον πιο κοντινό λόγο",
    reasonNotWorking: "Δεν λειτούργησε",
    reasonHard: "Ήταν δύσκολο στη χρήση",
    reasonMissing: "Έλειπε μια λειτουργία",
    reasonPrivacy: "Απόρρητο ή δικαιώματα",
    reasonNoNeed: "Δεν το χρειάζομαι πια",
    reasonOther: "Κάτι άλλο",
    anythingElse: "Κάτι άλλο;",
    optional: "Προαιρετικό",
    notePlaceholder: "Ένα σύντομο σημείωμα μάς βοηθά να καταλάβουμε το πρόβλημα.",
    selectReasonNote: "Επιλέξτε λόγο για να προσθέσετε προαιρετικό σημείωμα.",
    sending: "Αποστολή…",
    sendFeedback: "Αποστολή σχολίων",
    skipFeedback: "Παράλειψη σχολίων",
    anonymousNotice: "Ανώνυμα · μην συμπεριλαμβάνετε προσωπικά στοιχεία",
    sendError: "Η αποστολή απέτυχε. Δοκιμάστε ξανά.",
    feedbackReceived: "Τα σχόλια ελήφθησαν",
    feedbackSkipped: "Τα σχόλια παραλείφθηκαν",
    thanksHelps: "Ευχαριστούμε — αυτό βοηθά.",
    noProblem: "Κανένα πρόβλημα.",
    sentAnonymously: "Η απάντησή σας στάλθηκε ανώνυμα.",
    nothingSent: "Δεν στάλθηκε ούτε αποθηκεύτηκε τίποτα.",
    exploreAll: "Εξερεύνηση όλων →",
  },
  bg: {
    pinFromExtensions: "Закачете от Разширения",
    installed: "Инсталирано",
    ready: "{name} е готово.",
    pinInstruction: "Закачете го от менюто „Разширения“ в Chrome, след това отворете {platform}.",
    open: "Отваряне на {platform}",
    readyWhen: "Готово, когато сте готови",
    privacyDesign: "Поверителност по замисъл",
    dataBrowser: "Данните ви остават в браузъра.",
    seeAccess: "Вижте точно до какво има достъп →",
    independent: "Независими инструменти за по-спокоен живот в социалните мрежи.",
    support: "Поддръжка",
    privacy: "Поверителност",
    more: "Още от CleanMySocial",
    explore: "Разгледайте →",
    free: "Безплатно",
    anonymousFeedback: "Анонимна обратна връзка",
    extensionUninstalled: "Разширението е деинсталирано",
    thanksTry: "Преди да си тръгнете…",
    uninstallQuestion: "Защо деинсталирахте {name}?",
    oneAnswer: "Изберете една причина — може да успеем да помогнем.",
    reinstall: "Инсталирайте отново {name} ↗",
    whatHappened: "Какво се случи?",
    chooseReason: "Изберете най-близката причина",
    reasonNotWorking: "Не работеше",
    reasonHard: "Беше трудно за използване",
    reasonMissing: "Липсваше функция",
    reasonPrivacy: "Поверителност или разрешения",
    reasonNoNeed: "Вече не ми трябва",
    reasonOther: "Нещо друго",
    anythingElse: "Нещо друго?",
    optional: "По избор",
    notePlaceholder: "Кратка бележка ще ни помогне да разберем проблема.",
    selectReasonNote: "Изберете причина, за да добавите бележка по избор.",
    sending: "Изпращане…",
    sendFeedback: "Изпращане на отзив",
    skipFeedback: "Пропускане на отзива",
    anonymousNotice: "Анонимно · не включвайте лична информация",
    sendError: "Изпращането не успя. Опитайте отново.",
    feedbackReceived: "Отзивът е получен",
    feedbackSkipped: "Отзивът е пропуснат",
    thanksHelps: "Благодарим — това помага.",
    noProblem: "Няма проблем.",
    sentAnonymously: "Отговорът ви беше изпратен анонимно.",
    nothingSent: "Нищо не беше изпратено или запазено.",
    exploreAll: "Разгледайте всички →",
  },
  sk: {
    pinFromExtensions: "Pripnúť z Rozšírení",
    installed: "Nainštalované",
    ready: "{name} je pripravené.",
    pinInstruction: "Pripnite ho z ponuky Rozšírenia v Chrome a potom otvorte {platform}.",
    open: "Otvoriť {platform}",
    readyWhen: "Pripravené, keď budete vy",
    privacyDesign: "Súkromie už v návrhu",
    dataBrowser: "Vaše údaje zostávajú v prehliadači.",
    seeAccess: "Pozrite si presne, k čomu má prístup →",
    independent: "Nezávislé nástroje pre pokojnejší sociálny život.",
    support: "Podpora",
    privacy: "Súkromie",
    more: "Viac od CleanMySocial",
    explore: "Preskúmať →",
    free: "Zadarmo",
    anonymousFeedback: "Anonymná spätná väzba",
    extensionUninstalled: "Rozšírenie bolo odinštalované",
    thanksTry: "Kým odídete…",
    uninstallQuestion: "Prečo ste odinštalovali {name}?",
    oneAnswer: "Vyberte jeden dôvod — možno vám dokážeme pomôcť.",
    reinstall: "Znova nainštalovať {name} ↗",
    whatHappened: "Čo sa stalo?",
    chooseReason: "Vyberte najbližší dôvod",
    reasonNotWorking: "Nefungovalo to",
    reasonHard: "Bolo náročné na používanie",
    reasonMissing: "Chýbala funkcia",
    reasonPrivacy: "Súkromie alebo povolenia",
    reasonNoNeed: "Už to nepotrebujem",
    reasonOther: "Niečo iné",
    anythingElse: "Ešte niečo?",
    optional: "Voliteľné",
    notePlaceholder: "Krátka poznámka nám pomôže pochopiť problém.",
    selectReasonNote: "Vyberte dôvod a pridajte voliteľnú poznámku.",
    sending: "Odosiela sa…",
    sendFeedback: "Odoslať spätnú väzbu",
    skipFeedback: "Preskočiť spätnú väzbu",
    anonymousNotice: "Anonymné · neuvádzajte osobné údaje",
    sendError: "Odoslanie zlyhalo. Skúste to znova.",
    feedbackReceived: "Spätná väzba prijatá",
    feedbackSkipped: "Spätná väzba preskočená",
    thanksHelps: "Ďakujeme — pomáha nám to.",
    noProblem: "Žiadny problém.",
    sentAnonymously: "Vaša odpoveď bola odoslaná anonymne.",
    nothingSent: "Nič sa neodoslalo ani neuložilo.",
    exploreAll: "Preskúmať všetko →",
  },
  hr: {
    pinFromExtensions: "Prikvačite iz Proširenja",
    installed: "Instalirano",
    ready: "{name} je spreman.",
    pinInstruction: "Prikvačite ga iz izbornika Proširenja u Chromeu, a zatim otvorite {platform}.",
    open: "Otvori {platform}",
    readyWhen: "Spremno kad i vi",
    privacyDesign: "Privatnost od samog početka",
    dataBrowser: "Vaši podaci ostaju u pregledniku.",
    seeAccess: "Pogledajte točno čemu pristupa →",
    independent: "Neovisni alati za mirniji društveni život.",
    support: "Podrška",
    privacy: "Privatnost",
    more: "Više od CleanMySocial",
    explore: "Istražite →",
    free: "Besplatno",
    anonymousFeedback: "Anonimne povratne informacije",
    extensionUninstalled: "Proširenje je deinstalirano",
    thanksTry: "Prije nego što odete…",
    uninstallQuestion: "Zašto ste deinstalirali {name}?",
    oneAnswer: "Odaberite jedan razlog — možda vam možemo pomoći.",
    reinstall: "Ponovno instalirajte {name} ↗",
    whatHappened: "Što se dogodilo?",
    chooseReason: "Odaberite najbliži razlog",
    reasonNotWorking: "Nije radilo",
    reasonHard: "Bilo je teško za korištenje",
    reasonMissing: "Nedostajala je značajka",
    reasonPrivacy: "Privatnost ili dopuštenja",
    reasonNoNeed: "Više mi ne treba",
    reasonOther: "Nešto drugo",
    anythingElse: "Još nešto?",
    optional: "Neobavezno",
    notePlaceholder: "Kratka bilješka pomoći će nam razumjeti problem.",
    selectReasonNote: "Odaberite razlog da biste dodali neobaveznu bilješku.",
    sending: "Slanje…",
    sendFeedback: "Pošalji povratne informacije",
    skipFeedback: "Preskoči povratne informacije",
    anonymousNotice: "Anonimno · nemojte navoditi osobne podatke",
    sendError: "Slanje nije uspjelo. Pokušajte ponovno.",
    feedbackReceived: "Povratne informacije primljene",
    feedbackSkipped: "Povratne informacije preskočene",
    thanksHelps: "Hvala — to pomaže.",
    noProblem: "Nema problema.",
    sentAnonymously: "Vaš je odgovor poslan anonimno.",
    nothingSent: "Ništa nije poslano ni spremljeno.",
    exploreAll: "Istražite sve →",
  },
  sl: {
    pinFromExtensions: "Pripnite iz Razširitev",
    installed: "Nameščeno",
    ready: "{name} je pripravljen.",
    pinInstruction: "Pripnite ga iz menija Razširitve v Chromu in nato odprite {platform}.",
    open: "Odpri {platform}",
    readyWhen: "Pripravljeno, ko boste vi",
    privacyDesign: "Zasebnost že v zasnovi",
    dataBrowser: "Vaši podatki ostanejo v brskalniku.",
    seeAccess: "Oglejte si natanko, do česa dostopa →",
    independent: "Neodvisna orodja za mirnejše družbeno življenje.",
    support: "Podpora",
    privacy: "Zasebnost",
    more: "Več od CleanMySocial",
    explore: "Raziščite →",
    free: "Brezplačno",
    anonymousFeedback: "Anonimne povratne informacije",
    extensionUninstalled: "Razširitev je odstranjena",
    thanksTry: "Preden odidete…",
    uninstallQuestion: "Zakaj ste odstranili {name}?",
    oneAnswer: "Izberite en razlog — morda vam lahko pomagamo.",
    reinstall: "Znova namestite {name} ↗",
    whatHappened: "Kaj se je zgodilo?",
    chooseReason: "Izberite najbližji razlog",
    reasonNotWorking: "Ni delovalo",
    reasonHard: "Bilo je težko za uporabo",
    reasonMissing: "Manjkala je funkcija",
    reasonPrivacy: "Zasebnost ali dovoljenja",
    reasonNoNeed: "Ne potrebujem ga več",
    reasonOther: "Nekaj drugega",
    anythingElse: "Še kaj?",
    optional: "Neobvezno",
    notePlaceholder: "Kratka opomba nam pomaga razumeti težavo.",
    selectReasonNote: "Izberite razlog, da dodate neobvezno opombo.",
    sending: "Pošiljanje…",
    sendFeedback: "Pošlji povratne informacije",
    skipFeedback: "Preskoči povratne informacije",
    anonymousNotice: "Anonimno · ne navajajte osebnih podatkov",
    sendError: "Pošiljanje ni uspelo. Poskusite znova.",
    feedbackReceived: "Povratne informacije prejete",
    feedbackSkipped: "Povratne informacije preskočene",
    thanksHelps: "Hvala — to pomaga.",
    noProblem: "Ni težav.",
    sentAnonymously: "Vaš odgovor je bil poslan anonimno.",
    nothingSent: "Nič ni bilo poslano ali shranjeno.",
    exploreAll: "Raziščite vse →",
  },
  ms: {
    pinFromExtensions: "Semat daripada Sambungan",
    installed: "Dipasang",
    ready: "{name} sedia digunakan.",
    pinInstruction: "Semat daripada menu Sambungan Chrome, kemudian buka {platform}.",
    open: "Buka {platform}",
    readyWhen: "Sedia bila-bila masa",
    privacyDesign: "Privasi sejak reka bentuk",
    dataBrowser: "Data anda kekal dalam pelayar.",
    seeAccess: "Lihat dengan tepat apa yang diakses →",
    independent: "Alat bebas untuk kehidupan sosial yang lebih tenang.",
    support: "Sokongan",
    privacy: "Privasi",
    more: "Lagi daripada CleanMySocial",
    explore: "Teroka →",
    free: "Percuma",
    anonymousFeedback: "Maklum balas tanpa nama",
    extensionUninstalled: "Sambungan dinyahpasang",
    thanksTry: "Sebelum anda pergi…",
    uninstallQuestion: "Mengapa anda menyahpasang {name}?",
    oneAnswer: "Pilih satu sebab — kami mungkin boleh membantu.",
    reinstall: "Pasang semula {name} ↗",
    whatHappened: "Apa yang berlaku?",
    chooseReason: "Pilih sebab yang paling hampir",
    reasonNotWorking: "Ia tidak berfungsi",
    reasonHard: "Ia sukar digunakan",
    reasonMissing: "Ada ciri yang tiada",
    reasonPrivacy: "Privasi atau kebenaran",
    reasonNoNeed: "Saya tidak memerlukannya lagi",
    reasonOther: "Sebab lain",
    anythingElse: "Ada apa-apa lagi?",
    optional: "Pilihan",
    notePlaceholder: "Nota ringkas boleh membantu kami memahami masalah.",
    selectReasonNote: "Pilih sebab untuk menambah nota pilihan.",
    sending: "Menghantar…",
    sendFeedback: "Hantar maklum balas",
    skipFeedback: "Langkau maklum balas",
    anonymousNotice: "Tanpa nama · jangan sertakan maklumat peribadi",
    sendError: "Tidak dapat dihantar. Sila cuba sekali lagi.",
    feedbackReceived: "Maklum balas diterima",
    feedbackSkipped: "Maklum balas dilangkau",
    thanksHelps: "Terima kasih — itu membantu.",
    noProblem: "Tiada masalah.",
    sentAnonymously: "Jawapan anda dihantar tanpa nama.",
    nothingSent: "Tiada apa-apa dihantar atau disimpan.",
    exploreAll: "Teroka semua →",
  },
  uk: {
    pinFromExtensions: "Закріпіть у меню розширень",
    installed: "Встановлено",
    ready: "{name} готове до роботи.",
    pinInstruction: "Закріпіть його в меню «Розширення» Chrome, а потім відкрийте {platform}.",
    open: "Відкрити {platform}",
    readyWhen: "Готово, коли будете готові ви",
    privacyDesign: "Приватність за замовчуванням",
    dataBrowser: "Ваші дані залишаються у браузері.",
    seeAccess: "Подивіться, до чого саме є доступ →",
    independent: "Незалежні інструменти для спокійнішого життя в соцмережах.",
    support: "Підтримка",
    privacy: "Конфіденційність",
    more: "Більше від CleanMySocial",
    explore: "Переглянути →",
    free: "Безкоштовно",
    anonymousFeedback: "Анонімний відгук",
    extensionUninstalled: "Розширення видалено",
    thanksTry: "Перш ніж піти…",
    uninstallQuestion: "Чому ви видалили {name}?",
    oneAnswer: "Оберіть одну причину — можливо, ми зможемо допомогти.",
    reinstall: "Встановити {name} знову ↗",
    whatHappened: "Що сталося?",
    chooseReason: "Оберіть найближчу причину",
    reasonNotWorking: "Воно не працювало",
    reasonHard: "Ним було складно користуватися",
    reasonMissing: "Бракувало функції",
    reasonPrivacy: "Приватність або дозволи",
    reasonNoNeed: "Мені це більше не потрібно",
    reasonOther: "Інша причина",
    anythingElse: "Щось іще?",
    optional: "Необов’язково",
    notePlaceholder: "Коротка примітка допоможе нам зрозуміти проблему.",
    selectReasonNote: "Оберіть причину, щоб додати необов’язкову примітку.",
    sending: "Надсилання…",
    sendFeedback: "Надіслати відгук",
    skipFeedback: "Пропустити відгук",
    anonymousNotice: "Анонімно · не вказуйте особисту інформацію",
    sendError: "Не вдалося надіслати. Спробуйте ще раз.",
    feedbackReceived: "Відгук отримано",
    feedbackSkipped: "Відгук пропущено",
    thanksHelps: "Дякуємо — це допомагає.",
    noProblem: "Без проблем.",
    sentAnonymously: "Вашу відповідь надіслано анонімно.",
    nothingSent: "Нічого не надіслано й не збережено.",
    exploreAll: "Переглянути все →",
  },
  lt: {
    pinFromExtensions: "Prisekite iš plėtinių meniu",
    installed: "Įdiegta",
    ready: "{name} paruoštas.",
    pinInstruction: "Prisekite jį iš „Chrome“ plėtinių meniu, tada atidarykite {platform}.",
    open: "Atidaryti {platform}",
    readyWhen: "Pasiruošę, kai būsite pasiruošę jūs",
    privacyDesign: "Privatumas nuo pat pradžių",
    dataBrowser: "Jūsų duomenys lieka naršyklėje.",
    seeAccess: "Pažiūrėkite, prie ko tiksliai jis prieina →",
    independent: "Nepriklausomi įrankiai ramesniam gyvenimui socialiniuose tinkluose.",
    support: "Pagalba",
    privacy: "Privatumas",
    more: "Daugiau iš CleanMySocial",
    explore: "Naršyti →",
    free: "Nemokama",
    anonymousFeedback: "Anoniminis atsiliepimas",
    extensionUninstalled: "Plėtinys pašalintas",
    thanksTry: "Prieš išeinant…",
    uninstallQuestion: "Kodėl pašalinote {name}?",
    oneAnswer: "Pasirinkite vieną priežastį — galbūt galime padėti.",
    reinstall: "Įdiegti {name} iš naujo ↗",
    whatHappened: "Kas nutiko?",
    chooseReason: "Pasirinkite artimiausią priežastį",
    reasonNotWorking: "Neveikė",
    reasonHard: "Buvo sunku naudotis",
    reasonMissing: "Trūko funkcijos",
    reasonPrivacy: "Privatumas arba leidimai",
    reasonNoNeed: "Man to nebereikia",
    reasonOther: "Kita priežastis",
    anythingElse: "Dar kas nors?",
    optional: "Neprivaloma",
    notePlaceholder: "Trumpa pastaba padės mums suprasti problemą.",
    selectReasonNote: "Pasirinkite priežastį, kad pridėtumėte neprivalomą pastabą.",
    sending: "Siunčiama…",
    sendFeedback: "Siųsti atsiliepimą",
    skipFeedback: "Praleisti atsiliepimą",
    anonymousNotice: "Anonimiška · neįtraukite asmeninės informacijos",
    sendError: "Nepavyko išsiųsti. Bandykite dar kartą.",
    feedbackReceived: "Atsiliepimas gautas",
    feedbackSkipped: "Atsiliepimas praleistas",
    thanksHelps: "Ačiū — tai padeda.",
    noProblem: "Jokių problemų.",
    sentAnonymously: "Jūsų atsakymas išsiųstas anonimiškai.",
    nothingSent: "Niekas nebuvo išsiųsta ar išsaugota.",
    exploreAll: "Naršyti viską →",
  },
  lv: {
    pinFromExtensions: "Piespraudiet no paplašinājumu izvēlnes",
    installed: "Instalēts",
    ready: "{name} ir gatavs.",
    pinInstruction: "Piespraudiet to Chrome paplašinājumu izvēlnē un pēc tam atveriet {platform}.",
    open: "Atvērt {platform}",
    readyWhen: "Gatavs, kad būsiet gatavs jūs",
    privacyDesign: "Privātums jau no paša sākuma",
    dataBrowser: "Jūsu dati paliek pārlūkā.",
    seeAccess: "Skatiet, kam tieši tas piekļūst →",
    independent: "Neatkarīgi rīki mierīgākai dzīvei sociālajos tīklos.",
    support: "Atbalsts",
    privacy: "Privātums",
    more: "Vairāk no CleanMySocial",
    explore: "Izpētīt →",
    free: "Bezmaksas",
    anonymousFeedback: "Anonīma atsauksme",
    extensionUninstalled: "Paplašinājums atinstalēts",
    thanksTry: "Pirms dodaties prom…",
    uninstallQuestion: "Kāpēc atinstalējāt {name}?",
    oneAnswer: "Izvēlieties vienu iemeslu — iespējams, varam palīdzēt.",
    reinstall: "Instalēt {name} vēlreiz ↗",
    whatHappened: "Kas notika?",
    chooseReason: "Izvēlieties tuvāko iemeslu",
    reasonNotWorking: "Tas nedarbojās",
    reasonHard: "To bija grūti lietot",
    reasonMissing: "Trūka funkcijas",
    reasonPrivacy: "Privātums vai atļaujas",
    reasonNoNeed: "Man tas vairs nav vajadzīgs",
    reasonOther: "Kas cits",
    anythingElse: "Vēl kaut kas?",
    optional: "Pēc izvēles",
    notePlaceholder: "Īsa piezīme palīdzēs mums saprast problēmu.",
    selectReasonNote: "Izvēlieties iemeslu, lai pievienotu piezīmi pēc izvēles.",
    sending: "Sūta…",
    sendFeedback: "Sūtīt atsauksmi",
    skipFeedback: "Izlaist atsauksmi",
    anonymousNotice: "Anonīmi · nenorādiet personisko informāciju",
    sendError: "Neizdevās nosūtīt. Mēģiniet vēlreiz.",
    feedbackReceived: "Atsauksme saņemta",
    feedbackSkipped: "Atsauksme izlaista",
    thanksHelps: "Paldies — tas palīdz.",
    noProblem: "Nekādu problēmu.",
    sentAnonymously: "Jūsu atbilde tika nosūtīta anonīmi.",
    nothingSent: "Nekas netika nosūtīts vai saglabāts.",
    exploreAll: "Izpētīt visu →",
  },
  et: {
    pinFromExtensions: "Kinnita laienduste menüüst",
    installed: "Paigaldatud",
    ready: "{name} on valmis.",
    pinInstruction: "Kinnita see Chrome'i laienduste menüüst ja ava seejärel {platform}.",
    open: "Ava {platform}",
    readyWhen: "Valmis, kui sina oled",
    privacyDesign: "Privaatsus algusest peale",
    dataBrowser: "Sinu andmed jäävad brauserisse.",
    seeAccess: "Vaata täpselt, millele see ligi pääseb →",
    independent: "Sõltumatud tööriistad rahulikumaks sotsiaalmeediaeluks.",
    support: "Tugi",
    privacy: "Privaatsus",
    more: "Veel CleanMySocialilt",
    explore: "Avasta →",
    free: "Tasuta",
    anonymousFeedback: "Anonüümne tagasiside",
    extensionUninstalled: "Laiendus eemaldati",
    thanksTry: "Enne kui lahkud…",
    uninstallQuestion: "Miks sa {name} eemaldasid?",
    oneAnswer: "Vali üks põhjus — võib-olla saame aidata.",
    reinstall: "Paigalda {name} uuesti ↗",
    whatHappened: "Mis juhtus?",
    chooseReason: "Vali kõige lähedasem põhjus",
    reasonNotWorking: "See ei töötanud",
    reasonHard: "Seda oli raske kasutada",
    reasonMissing: "Mõni funktsioon puudus",
    reasonPrivacy: "Privaatsus või õigused",
    reasonNoNeed: "Mul pole seda enam vaja",
    reasonOther: "Midagi muud",
    anythingElse: "Veel midagi?",
    optional: "Valikuline",
    notePlaceholder: "Lühike märkus aitab meil probleemi mõista.",
    selectReasonNote: "Vali põhjus, et lisada valikuline märkus.",
    sending: "Saatmine…",
    sendFeedback: "Saada tagasiside",
    skipFeedback: "Jäta tagasiside vahele",
    anonymousNotice: "Anonüümne · ära lisa isikuandmeid",
    sendError: "Saatmine ebaõnnestus. Proovi uuesti.",
    feedbackReceived: "Tagasiside saadud",
    feedbackSkipped: "Tagasiside vahele jäetud",
    thanksHelps: "Aitäh — see aitab.",
    noProblem: "Pole probleemi.",
    sentAnonymously: "Sinu vastus saadeti anonüümselt.",
    nothingSent: "Midagi ei saadetud ega salvestatud.",
    exploreAll: "Avasta kõiki →",
  },
  hi: {
    pinFromExtensions: "एक्सटेंशन मेन्यू से पिन करें",
    installed: "इंस्टॉल हो गया",
    ready: "{name} तैयार है।",
    pinInstruction: "इसे Chrome के एक्सटेंशन मेन्यू से पिन करें, फिर {platform} खोलें।",
    open: "{platform} खोलें",
    readyWhen: "जब आप तैयार हों",
    privacyDesign: "डिज़ाइन से ही निजता",
    dataBrowser: "आपका डेटा आपके ब्राउज़र में ही रहता है।",
    seeAccess: "देखें कि यह ठीक-ठीक किन चीज़ों तक पहुँचता है →",
    independent: "सोशल मीडिया पर शांत जीवन के लिए स्वतंत्र टूल।",
    support: "सहायता",
    privacy: "निजता",
    more: "CleanMySocial से और टूल",
    explore: "देखें →",
    free: "मुफ़्त",
    anonymousFeedback: "गुमनाम फ़ीडबैक",
    extensionUninstalled: "एक्सटेंशन अनइंस्टॉल हो गया",
    thanksTry: "जाने से पहले…",
    uninstallQuestion: "आपने {name} को अनइंस्टॉल क्यों किया?",
    oneAnswer: "एक कारण चुनें — शायद हम मदद कर सकें।",
    reinstall: "{name} फिर से इंस्टॉल करें ↗",
    whatHappened: "क्या हुआ?",
    chooseReason: "सबसे नज़दीकी कारण चुनें",
    reasonNotWorking: "यह काम नहीं कर रहा था",
    reasonHard: "इसे इस्तेमाल करना मुश्किल था",
    reasonMissing: "कोई फ़ीचर नहीं था",
    reasonPrivacy: "निजता या अनुमतियाँ",
    reasonNoNeed: "अब मुझे इसकी ज़रूरत नहीं है",
    reasonOther: "कुछ और",
    anythingElse: "कुछ और कहना है?",
    optional: "वैकल्पिक",
    notePlaceholder: "एक छोटा नोट हमें समस्या समझने में मदद कर सकता है।",
    selectReasonNote: "वैकल्पिक नोट जोड़ने के लिए कोई कारण चुनें।",
    sending: "भेजा जा रहा है…",
    sendFeedback: "फ़ीडबैक भेजें",
    skipFeedback: "फ़ीडबैक छोड़ें",
    anonymousNotice: "गुमनाम · कृपया निजी जानकारी शामिल न करें",
    sendError: "भेजा नहीं जा सका। कृपया एक बार फिर कोशिश करें।",
    feedbackReceived: "फ़ीडबैक मिल गया",
    feedbackSkipped: "फ़ीडबैक छोड़ दिया गया",
    thanksHelps: "धन्यवाद — इससे मदद मिलती है।",
    noProblem: "कोई बात नहीं।",
    sentAnonymously: "आपका जवाब गुमनाम रूप से भेजा गया।",
    nothingSent: "कुछ भी भेजा या सहेजा नहीं गया।",
    exploreAll: "सभी देखें →",
  },
  fil: {
    pinFromExtensions: "I-pin mula sa Extensions",
    installed: "Na-install",
    ready: "Handa na ang {name}.",
    pinInstruction: "I-pin ito mula sa Extensions menu ng Chrome, pagkatapos buksan ang {platform}.",
    open: "Buksan ang {platform}",
    readyWhen: "Handa kapag handa ka",
    privacyDesign: "Privacy mula sa simula",
    dataBrowser: "Nananatili ang iyong data sa iyong browser.",
    seeAccess: "Tingnan nang eksakto kung ano ang ina-access nito →",
    independent: "Mga independiyenteng tool para sa mas tahimik na social life.",
    support: "Suporta",
    privacy: "Privacy",
    more: "Higit pa mula sa CleanMySocial",
    explore: "Tuklasin →",
    free: "Libre",
    anonymousFeedback: "Anonimong feedback",
    extensionUninstalled: "Na-uninstall ang extension",
    thanksTry: "Bago umalis…",
    uninstallQuestion: "Bakit in-uninstall ang {name}?",
    oneAnswer: "Pumili ng isang dahilan — maaari kaming tumulong.",
    reinstall: "I-install muli ang {name} ↗",
    whatHappened: "Ano ang nangyari?",
    chooseReason: "Piliin ang pinakamalapit na dahilan",
    reasonNotWorking: "Hindi gumana",
    reasonHard: "Mahirap gamitin",
    reasonMissing: "May nawawalang feature",
    reasonPrivacy: "Privacy o mga permiso",
    reasonNoNeed: "Hindi ko na kailangan",
    reasonOther: "Iba pang dahilan",
    anythingElse: "May iba pa?",
    optional: "Opsyonal",
    notePlaceholder: "Makatutulong ang maikling note para maunawaan ang problema.",
    selectReasonNote: "Pumili ng dahilan para magdagdag ng opsyonal na note.",
    sending: "Ipinapadala…",
    sendFeedback: "Ipadala ang feedback",
    skipFeedback: "Laktawan ang feedback",
    anonymousNotice: "Anonimo · huwag isama ang personal na impormasyon",
    sendError: "Hindi naipadala. Pakisubukan muli.",
    feedbackReceived: "Natanggap ang feedback",
    feedbackSkipped: "Nilaktawan ang feedback",
    thanksHelps: "Salamat — nakatutulong ito.",
    noProblem: "Walang problema.",
    sentAnonymously: "Ipinadala nang anonimo ang iyong sagot.",
    nothingSent: "Walang ipinadala o inimbak.",
    exploreAll: "Tuklasin ang lahat →",
  },
};

export function lifecycleCopy(locale: Locale): LifecycleCopy {
  return locale === "en" ? EN : TRANSLATIONS[locale] ?? EN;
}

export function formatCopy(template: string, values: Record<string, string>): string {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, value),
    template,
  );
}
