import type { Locale } from "./locales";

export interface PurchaseCopy {
  allExtensions: string;
  viewStore: string;
  privacyPolicy: string;
  showMore: string;
  showLess: string;
  extensionDetected: string;
  trusted: string;
  user: string;
  users: string;
  chooseAccess: string;
  choosePlan: string;
  pass: string;
  oneTime: string;
  monthly: string;
  cancelAnytime: string;
  recommended: string;
  lifetime: string;
  forever: string;
  getPass: string;
  startMonthly: string;
  getLifetime: string;
  perMonth: string;
  availableSoon: string;
  chooseOption: string;
  secureInstant: string;
  secureCheckout: string;
  whereKey: string;
  emailLabel: string;
  emailHint: string;
  continueCheckout: string;
  openingCheckout: string;
  back: string;
  moneyBack: string;
  moneyBackDetail: string;
  secureCreem: string;
  encrypted: string;
  noSubscription: string;
  manageCancel: string;
  passAccess: string;
  lifetimeAccess: string;
  guarantees: string;
  invalidEmail: string;
  checkoutError: string;
  genericError: string;
}

const en: PurchaseCopy = {
  allExtensions: "All extensions", viewStore: "View on the Chrome Web Store", privacyPolicy: "Privacy policy", showMore: "Show more", showLess: "Show less", extensionDetected: "Extension detected · Already installed",
  trusted: "Trusted by", user: "user", users: "users", chooseAccess: "Choose your access", choosePlan: "Choose a plan",
  pass: "🔥 3-Day Pass", oneTime: "One-time payment", monthly: "Monthly", cancelAnytime: "Cancel anytime", recommended: "Recommended",
  lifetime: "Lifetime", forever: "One payment · yours forever", getPass: "Get 3-Day Access", startMonthly: "Start Monthly", getLifetime: "Get Lifetime", perMonth: "/mo", availableSoon: "Available shortly", chooseOption: "Choose an option",
  secureInstant: "Secure payment · Instant access", secureCheckout: "Secure checkout", whereKey: "Where should we send your license key?",
  emailLabel: "Email for your license key", emailHint: "We email your key after payment and show it on the next page. Paste it into the extension to activate. Your address is used only for your license and support.",
  continueCheckout: "Continue to secure checkout", openingCheckout: "Opening secure checkout…", back: "← Back",
  moneyBack: "14-day money back", moneyBackDetail: "Not happy? Get a full refund.", secureCreem: "Secure checkout by Creem", encrypted: "Encrypted and secure payment processed by Creem.",
  noSubscription: "No subscription", manageCancel: "Manage or cancel your subscription whenever you want.", passAccess: "One payment. Full Pro access for 3 days.", lifetimeAccess: "One payment. Use it forever.", guarantees: "Purchase guarantees",
  invalidEmail: "Enter the email address where we should send your license key.", checkoutError: "Could not start checkout.", genericError: "Something went wrong.",
};

const COPY: Record<Locale, PurchaseCopy> = {
  en,
  es: { ...en, trusted:"Con la confianza de",user:"usuario",users:"usuarios",chooseAccess:"Elige tu acceso",choosePlan:"Elige un plan",pass:"🔥 Pase de 3 días",oneTime:"Pago único",monthly:"Mensual",cancelAnytime:"Cancela cuando quieras",recommended:"Recomendado",lifetime:"De por vida",forever:"Un pago · para siempre",getPass:"Obtener acceso por 3 días",startMonthly:"Iniciar plan mensual",getLifetime:"Obtener acceso de por vida",perMonth:"/mes",secureInstant:"Pago seguro · Acceso instantáneo",secureCheckout:"Pago seguro",whereKey:"¿Dónde enviamos tu clave de licencia?",emailLabel:"Correo para tu clave de licencia",emailHint:"Te enviaremos la clave después del pago y la mostraremos en la página siguiente. Pégala en la extensión para activarla. Solo usamos tu correo para la licencia y el soporte.",continueCheckout:"Continuar al pago seguro",openingCheckout:"Abriendo el pago seguro…",back:"← Atrás",moneyBack:"Garantía de 14 días",moneyBackDetail:"¿No te convence? Recibe un reembolso completo.",secureCreem:"Pago seguro con Creem",encrypted:"Pago cifrado y seguro procesado por Creem.",noSubscription:"Sin suscripción",manageCancel:"Administra o cancela tu suscripción cuando quieras.",passAccess:"Un pago. Acceso Pro completo durante 3 días.",lifetimeAccess:"Un pago. Úsalo para siempre.",guarantees:"Garantías de compra",invalidEmail:"Introduce el correo donde debemos enviar tu clave de licencia.",checkoutError:"No se pudo iniciar el pago.",genericError:"Algo salió mal." },
  de: { ...en, trusted:"Vertraut von",user:"Nutzer",users:"Nutzern",chooseAccess:"Zugang wählen",choosePlan:"Tarif wählen",pass:"🔥 3-Tage-Pass",oneTime:"Einmalige Zahlung",monthly:"Monatlich",cancelAnytime:"Jederzeit kündbar",recommended:"Empfohlen",lifetime:"Lebenslang",forever:"Einmal zahlen · für immer",getPass:"3-Tage-Zugang sichern",startMonthly:"Monatlich starten",getLifetime:"Lebenslangen Zugang sichern",perMonth:"/Monat",secureInstant:"Sichere Zahlung · Sofortiger Zugang",secureCheckout:"Sicherer Checkout",whereKey:"Wohin sollen wir deinen Lizenzschlüssel senden?",emailLabel:"E-Mail für deinen Lizenzschlüssel",emailHint:"Wir senden deinen Schlüssel nach der Zahlung per E-Mail und zeigen ihn auf der nächsten Seite. Füge ihn zur Aktivierung in die Erweiterung ein.",continueCheckout:"Weiter zum sicheren Checkout",openingCheckout:"Sicherer Checkout wird geöffnet…",back:"← Zurück",moneyBack:"14 Tage Geld zurück",moneyBackDetail:"Nicht zufrieden? Volle Rückerstattung.",secureCreem:"Sicherer Checkout mit Creem",encrypted:"Verschlüsselte, sichere Zahlung über Creem.",noSubscription:"Kein Abonnement",manageCancel:"Verwalte oder kündige dein Abo jederzeit.",passAccess:"Eine Zahlung. 3 Tage voller Pro-Zugang.",lifetimeAccess:"Eine Zahlung. Für immer nutzen.",guarantees:"Kaufgarantien",invalidEmail:"Gib die E-Mail-Adresse für deinen Lizenzschlüssel ein.",checkoutError:"Checkout konnte nicht gestartet werden.",genericError:"Etwas ist schiefgelaufen." },
  fr: { ...en, trusted:"Adopté par",user:"utilisateur",users:"utilisateurs",chooseAccess:"Choisissez votre accès",choosePlan:"Choisissez une formule",pass:"🔥 Pass 3 jours",oneTime:"Paiement unique",monthly:"Mensuel",cancelAnytime:"Résiliable à tout moment",recommended:"Recommandé",lifetime:"À vie",forever:"Un paiement · à vie",getPass:"Obtenir 3 jours d’accès",startMonthly:"Commencer le forfait mensuel",getLifetime:"Obtenir l’accès à vie",perMonth:"/mois",secureInstant:"Paiement sécurisé · Accès immédiat",secureCheckout:"Paiement sécurisé",whereKey:"Où envoyer votre clé de licence ?",emailLabel:"E-mail pour votre clé",emailHint:"Nous envoyons votre clé après le paiement et l’affichons sur la page suivante. Collez-la dans l’extension pour l’activer.",continueCheckout:"Continuer vers le paiement",openingCheckout:"Ouverture du paiement sécurisé…",back:"← Retour",moneyBack:"Remboursement sous 14 jours",moneyBackDetail:"Pas satisfait ? Remboursement intégral.",secureCreem:"Paiement sécurisé par Creem",encrypted:"Paiement chiffré et sécurisé traité par Creem.",noSubscription:"Sans abonnement",manageCancel:"Gérez ou résiliez votre abonnement à tout moment.",passAccess:"Un paiement. Accès Pro complet pendant 3 jours.",lifetimeAccess:"Un paiement. Utilisez-le à vie.",guarantees:"Garanties d’achat",invalidEmail:"Saisissez l’e-mail auquel envoyer votre clé.",checkoutError:"Impossible de démarrer le paiement.",genericError:"Une erreur est survenue." },
  it: { ...en, trusted:"Scelto da",user:"utente",users:"utenti",chooseAccess:"Scegli il tuo accesso",choosePlan:"Scegli un piano",pass:"🔥 Pass di 3 giorni",oneTime:"Pagamento unico",monthly:"Mensile",cancelAnytime:"Annulla quando vuoi",recommended:"Consigliato",lifetime:"A vita",forever:"Un pagamento · per sempre",getPass:"Ottieni 3 giorni di accesso",startMonthly:"Avvia il mensile",getLifetime:"Ottieni accesso a vita",perMonth:"/mese",secureInstant:"Pagamento sicuro · Accesso immediato",secureCheckout:"Pagamento sicuro",whereKey:"Dove inviamo la chiave di licenza?",emailLabel:"Email per la chiave",emailHint:"Invieremo la chiave dopo il pagamento e la mostreremo nella pagina successiva. Incollala nell’estensione per attivarla.",continueCheckout:"Continua al pagamento sicuro",openingCheckout:"Apertura del pagamento…",back:"← Indietro",moneyBack:"Rimborso entro 14 giorni",moneyBackDetail:"Non soddisfatto? Rimborso completo.",secureCreem:"Pagamento sicuro con Creem",encrypted:"Pagamento crittografato e sicuro gestito da Creem.",noSubscription:"Nessun abbonamento",manageCancel:"Gestisci o annulla l’abbonamento quando vuoi.",passAccess:"Un pagamento. Accesso Pro completo per 3 giorni.",lifetimeAccess:"Un pagamento. Usalo per sempre.",guarantees:"Garanzie di acquisto",invalidEmail:"Inserisci l’email a cui inviare la chiave.",checkoutError:"Impossibile avviare il pagamento.",genericError:"Qualcosa è andato storto." },
  pt_PT: { ...en, trusted:"Utilizado por",user:"utilizador",users:"utilizadores",chooseAccess:"Escolha o seu acesso",choosePlan:"Escolha um plano",pass:"🔥 Passe de 3 dias",oneTime:"Pagamento único",monthly:"Mensal",cancelAnytime:"Cancele quando quiser",recommended:"Recomendado",lifetime:"Vitalício",forever:"Um pagamento · para sempre",getPass:"Obter acesso por 3 dias",startMonthly:"Iniciar mensal",getLifetime:"Obter acesso vitalício",perMonth:"/mês",secureInstant:"Pagamento seguro · Acesso imediato",secureCheckout:"Pagamento seguro",whereKey:"Para onde enviamos a chave de licença?",emailLabel:"Email para a chave",emailHint:"Enviamos a chave após o pagamento e mostramos na página seguinte. Cole-a na extensão para ativar.",continueCheckout:"Continuar para pagamento",openingCheckout:"A abrir pagamento seguro…",back:"← Voltar",moneyBack:"Reembolso em 14 dias",moneyBackDetail:"Não está satisfeito? Reembolso total.",secureCreem:"Pagamento seguro com Creem",encrypted:"Pagamento encriptado e seguro processado pela Creem.",noSubscription:"Sem subscrição",manageCancel:"Gira ou cancele a subscrição quando quiser.",passAccess:"Um pagamento. Acesso Pro completo por 3 dias.",lifetimeAccess:"Um pagamento. Use para sempre.",guarantees:"Garantias de compra",invalidEmail:"Introduza o email para receber a chave.",checkoutError:"Não foi possível iniciar o pagamento.",genericError:"Algo correu mal." },
  pt_BR: { ...en, trusted:"Aprovado por",user:"usuário",users:"usuários",chooseAccess:"Escolha seu acesso",choosePlan:"Escolha um plano",pass:"🔥 Passe de 3 dias",oneTime:"Pagamento único",monthly:"Mensal",cancelAnytime:"Cancele quando quiser",recommended:"Recomendado",lifetime:"Vitalício",forever:"Um pagamento · para sempre",getPass:"Obter acesso por 3 dias",startMonthly:"Iniciar mensal",getLifetime:"Obter acesso vitalício",perMonth:"/mês",secureInstant:"Pagamento seguro · Acesso imediato",secureCheckout:"Pagamento seguro",whereKey:"Onde devemos enviar sua chave de licença?",emailLabel:"Email para sua chave",emailHint:"Enviamos sua chave após o pagamento e a mostramos na próxima página. Cole-a na extensão para ativar.",continueCheckout:"Continuar para o pagamento",openingCheckout:"Abrindo pagamento seguro…",back:"← Voltar",moneyBack:"Reembolso em 14 dias",moneyBackDetail:"Não gostou? Receba o reembolso total.",secureCreem:"Pagamento seguro com Creem",encrypted:"Pagamento criptografado e seguro processado pela Creem.",noSubscription:"Sem assinatura",manageCancel:"Gerencie ou cancele sua assinatura quando quiser.",passAccess:"Um pagamento. Acesso Pro completo por 3 dias.",lifetimeAccess:"Um pagamento. Use para sempre.",guarantees:"Garantias de compra",invalidEmail:"Digite o email para receber sua chave.",checkoutError:"Não foi possível iniciar o pagamento.",genericError:"Algo deu errado." },
  es_419: { ...en, ...({} as PurchaseCopy), trusted:"Con la confianza de",user:"usuario",users:"usuarios",chooseAccess:"Elige tu acceso",choosePlan:"Elige un plan",pass:"🔥 Pase de 3 días",oneTime:"Pago único",monthly:"Mensual",cancelAnytime:"Cancela cuando quieras",recommended:"Recomendado",lifetime:"De por vida",forever:"Un pago · para siempre",getPass:"Obtener acceso por 3 días",startMonthly:"Iniciar plan mensual",getLifetime:"Obtener acceso de por vida",perMonth:"/mes",secureInstant:"Pago seguro · Acceso inmediato",secureCheckout:"Pago seguro",whereKey:"¿Dónde enviamos tu clave de licencia?",emailLabel:"Correo para tu clave",emailHint:"Te enviaremos la clave después del pago y la mostraremos en la página siguiente. Pégala en la extensión para activarla.",continueCheckout:"Continuar al pago seguro",openingCheckout:"Abriendo el pago…",back:"← Atrás",moneyBack:"Garantía de 14 días",moneyBackDetail:"¿No te convence? Recibe un reembolso completo.",secureCreem:"Pago seguro con Creem",encrypted:"Pago cifrado y seguro procesado por Creem.",noSubscription:"Sin suscripción",manageCancel:"Administra o cancela tu suscripción cuando quieras.",passAccess:"Un pago. Acceso Pro completo durante 3 días.",lifetimeAccess:"Un pago. Úsalo para siempre.",guarantees:"Garantías de compra",invalidEmail:"Introduce el correo donde enviaremos tu clave.",checkoutError:"No se pudo iniciar el pago.",genericError:"Algo salió mal." },
  ja: { ...en, trusted:"利用者",user:"人",users:"人",chooseAccess:"アクセスを選択",choosePlan:"プランを選択",pass:"🔥 3日間パス",oneTime:"1回払い",monthly:"月額",cancelAnytime:"いつでも解約可能",recommended:"おすすめ",lifetime:"永久",forever:"1回払い・永久利用",getPass:"3日間アクセスを購入",startMonthly:"月額プランを開始",getLifetime:"永久アクセスを購入",perMonth:"/月",secureInstant:"安全な決済・すぐに利用可能",secureCheckout:"安全な決済",whereKey:"ライセンスキーの送信先は？",emailLabel:"ライセンスキー送信用メール",emailHint:"支払い後にキーをメールで送り、次のページにも表示します。拡張機能に貼り付けて有効化してください。",continueCheckout:"安全な決済へ進む",openingCheckout:"決済画面を開いています…",back:"← 戻る",moneyBack:"14日間返金保証",moneyBackDetail:"満足できない場合は全額返金します。",secureCreem:"Creemによる安全な決済",encrypted:"Creemが暗号化された安全な決済を処理します。",noSubscription:"サブスクリプションなし",manageCancel:"いつでも管理・解約できます。",passAccess:"1回払い。3日間Proをフル利用。",lifetimeAccess:"1回払い。永久に利用可能。",guarantees:"購入保証",invalidEmail:"キーの送信先メールを入力してください。",checkoutError:"決済を開始できませんでした。",genericError:"エラーが発生しました。" },
  ko: { ...en, trusted:"사용자",user:"명",users:"명",chooseAccess:"이용권 선택",choosePlan:"플랜 선택",pass:"🔥 3일 패스",oneTime:"일회성 결제",monthly:"월간",cancelAnytime:"언제든 취소",recommended:"추천",lifetime:"평생",forever:"한 번 결제 · 평생 이용",getPass:"3일 이용권 받기",startMonthly:"월간 시작",getLifetime:"평생 이용권 받기",perMonth:"/월",secureInstant:"안전한 결제 · 즉시 이용",secureCheckout:"안전한 결제",whereKey:"라이선스 키를 어디로 보내드릴까요?",emailLabel:"키를 받을 이메일",emailHint:"결제 후 키를 이메일로 보내고 다음 페이지에도 표시합니다. 확장 프로그램에 붙여넣어 활성화하세요.",continueCheckout:"안전한 결제로 계속",openingCheckout:"결제 화면 여는 중…",back:"← 뒤로",moneyBack:"14일 환불 보장",moneyBackDetail:"만족하지 않으면 전액 환불합니다.",secureCreem:"Creem 안전 결제",encrypted:"Creem이 암호화된 안전한 결제를 처리합니다.",noSubscription:"구독 없음",manageCancel:"언제든 구독을 관리하거나 취소하세요.",passAccess:"한 번 결제. 3일간 Pro 전체 이용.",lifetimeAccess:"한 번 결제. 평생 이용.",guarantees:"구매 보장",invalidEmail:"키를 받을 이메일을 입력하세요.",checkoutError:"결제를 시작할 수 없습니다.",genericError:"문제가 발생했습니다." },
  zh_TW: { ...en, trusted:"已有",user:"位使用者信賴",users:"位使用者信賴",chooseAccess:"選擇存取方案",choosePlan:"選擇方案",pass:"🔥 3 天方案",oneTime:"單次付款",monthly:"月費",cancelAnytime:"隨時取消",recommended:"推薦",lifetime:"永久",forever:"單次付款 · 永久使用",getPass:"取得 3 天權限",startMonthly:"開始月費方案",getLifetime:"取得永久權限",perMonth:"/月",secureInstant:"安全付款 · 立即存取",secureCheckout:"安全結帳",whereKey:"授權金鑰要寄到哪裡？",emailLabel:"接收授權金鑰的電子郵件",emailHint:"付款後我們會寄送金鑰，並在下一頁顯示。請貼到擴充功能中啟用。",continueCheckout:"前往安全結帳",openingCheckout:"正在開啟安全結帳…",back:"← 返回",moneyBack:"14 天退款保證",moneyBackDetail:"不滿意？可獲全額退款。",secureCreem:"由 Creem 安全結帳",encrypted:"由 Creem 處理加密安全付款。",noSubscription:"無訂閱",manageCancel:"可隨時管理或取消訂閱。",passAccess:"單次付款。完整 Pro 權限 3 天。",lifetimeAccess:"單次付款。永久使用。",guarantees:"購買保障",invalidEmail:"請輸入接收授權金鑰的電子郵件。",checkoutError:"無法開始結帳。",genericError:"發生錯誤。" },
  zh_CN: { ...en, trusted:"已有",user:"位用户信赖",users:"位用户信赖",chooseAccess:"选择访问方案",choosePlan:"选择方案",pass:"🔥 3 天方案",oneTime:"单次付款",monthly:"月付",cancelAnytime:"随时取消",recommended:"推荐",lifetime:"永久",forever:"单次付款 · 永久使用",getPass:"获取 3 天权限",startMonthly:"开始月付方案",getLifetime:"获取永久权限",perMonth:"/月",secureInstant:"安全付款 · 即时访问",secureCheckout:"安全结账",whereKey:"许可证密钥发送到哪里？",emailLabel:"接收许可证密钥的邮箱",emailHint:"付款后我们会通过邮件发送密钥，并在下一页显示。粘贴到扩展程序中即可激活。",continueCheckout:"前往安全结账",openingCheckout:"正在打开安全结账…",back:"← 返回",moneyBack:"14 天退款保证",moneyBackDetail:"不满意？可获全额退款。",secureCreem:"由 Creem 安全结账",encrypted:"由 Creem 处理加密安全付款。",noSubscription:"无订阅",manageCancel:"可随时管理或取消订阅。",passAccess:"单次付款。完整 Pro 权限 3 天。",lifetimeAccess:"单次付款。永久使用。",guarantees:"购买保障",invalidEmail:"请输入接收许可证密钥的邮箱。",checkoutError:"无法开始结账。",genericError:"出现错误。" },
  nl: { ...en, trusted:"Vertrouwd door",user:"gebruiker",users:"gebruikers",chooseAccess:"Kies je toegang",choosePlan:"Kies een plan",pass:"🔥 3-daagse pas",oneTime:"Eenmalige betaling",monthly:"Maandelijks",cancelAnytime:"Altijd opzegbaar",recommended:"Aanbevolen",lifetime:"Levenslang",forever:"Eén betaling · voor altijd",getPass:"Neem 3 dagen toegang",startMonthly:"Start maandelijks",getLifetime:"Neem levenslange toegang",perMonth:"/mnd",secureInstant:"Veilige betaling · Direct toegang",secureCheckout:"Veilig afrekenen",whereKey:"Waar sturen we je licentiesleutel heen?",emailLabel:"E-mail voor je licentiesleutel",emailHint:"We mailen je sleutel na betaling en tonen hem op de volgende pagina. Plak hem in de extensie om te activeren.",continueCheckout:"Verder naar veilig afrekenen",openingCheckout:"Beveiligde checkout openen…",back:"← Terug",moneyBack:"14 dagen geld terug",moneyBackDetail:"Niet tevreden? Volledige terugbetaling.",secureCreem:"Veilig afrekenen met Creem",encrypted:"Versleutelde, veilige betaling via Creem.",noSubscription:"Geen abonnement",manageCancel:"Beheer of annuleer wanneer je wilt.",passAccess:"Eén betaling. 3 dagen volledige Pro-toegang.",lifetimeAccess:"Eén betaling. Voor altijd gebruiken.",guarantees:"Aankoopgaranties",invalidEmail:"Vul het e-mailadres voor je sleutel in.",checkoutError:"Afrekenen kon niet worden gestart.",genericError:"Er ging iets mis." },
  pl: { ...en, trusted:"Zaufało nam",user:"użytkownik",users:"użytkowników",chooseAccess:"Wybierz dostęp",choosePlan:"Wybierz plan",pass:"🔥 Dostęp na 3 dni",oneTime:"Płatność jednorazowa",monthly:"Miesięcznie",cancelAnytime:"Anuluj w każdej chwili",recommended:"Polecane",lifetime:"Dożywotnio",forever:"Jedna płatność · na zawsze",getPass:"Kup dostęp na 3 dni",startMonthly:"Rozpocznij plan miesięczny",getLifetime:"Kup dostęp dożywotni",perMonth:"/mies.",secureInstant:"Bezpieczna płatność · Natychmiastowy dostęp",secureCheckout:"Bezpieczna płatność",whereKey:"Gdzie wysłać klucz licencyjny?",emailLabel:"E-mail dla klucza licencyjnego",emailHint:"Po płatności wyślemy klucz e-mailem i pokażemy go na następnej stronie. Wklej go w rozszerzeniu.",continueCheckout:"Przejdź do bezpiecznej płatności",openingCheckout:"Otwieranie płatności…",back:"← Wstecz",moneyBack:"14 dni na zwrot",moneyBackDetail:"Brak satysfakcji? Pełny zwrot.",secureCreem:"Bezpieczna płatność Creem",encrypted:"Szyfrowana bezpieczna płatność przez Creem.",noSubscription:"Bez subskrypcji",manageCancel:"Zarządzaj lub anuluj subskrypcję w każdej chwili.",passAccess:"Jedna płatność. Pełny Pro przez 3 dni.",lifetimeAccess:"Jedna płatność. Korzystaj zawsze.",guarantees:"Gwarancje zakupu",invalidEmail:"Wpisz e-mail, na który wysłać klucz.",checkoutError:"Nie udało się rozpocząć płatności.",genericError:"Coś poszło nie tak." },
  sv: { ...en, trusted:"Betrodd av",user:"användare",users:"användare",chooseAccess:"Välj åtkomst",choosePlan:"Välj plan",pass:"🔥 3-dagarspass",oneTime:"Engångsbetalning",monthly:"Månadsvis",cancelAnytime:"Avsluta när du vill",recommended:"Rekommenderad",lifetime:"Livstid",forever:"En betalning · för alltid",getPass:"Få 3 dagars åtkomst",startMonthly:"Starta månadsvis",getLifetime:"Få livstidsåtkomst",perMonth:"/mån",secureInstant:"Säker betalning · Direkt åtkomst",secureCheckout:"Säker betalning",whereKey:"Vart ska licensnyckeln skickas?",emailLabel:"E-post för licensnyckeln",emailHint:"Vi mejlar nyckeln efter betalning och visar den på nästa sida. Klistra in den i tillägget.",continueCheckout:"Fortsätt till säker betalning",openingCheckout:"Öppnar säker betalning…",back:"← Tillbaka",moneyBack:"14 dagars återbetalning",moneyBackDetail:"Inte nöjd? Full återbetalning.",secureCreem:"Säker betalning med Creem",encrypted:"Krypterad säker betalning via Creem.",noSubscription:"Ingen prenumeration",manageCancel:"Hantera eller avsluta när du vill.",passAccess:"En betalning. Full Pro i 3 dagar.",lifetimeAccess:"En betalning. Använd för alltid.",guarantees:"Köpgarantier",invalidEmail:"Ange e-postadressen för din nyckel.",checkoutError:"Kunde inte starta betalningen.",genericError:"Något gick fel." },
  da: { ...en, trusted:"Betroet af",user:"bruger",users:"brugere",chooseAccess:"Vælg adgang",choosePlan:"Vælg plan",pass:"🔥 3-dagespas",oneTime:"Engangsbetaling",monthly:"Månedlig",cancelAnytime:"Opsig når som helst",recommended:"Anbefalet",lifetime:"Livstid",forever:"Én betaling · for altid",getPass:"Få 3 dages adgang",startMonthly:"Start månedlig",getLifetime:"Få livstidsadgang",perMonth:"/md.",secureInstant:"Sikker betaling · Øjeblikkelig adgang",secureCheckout:"Sikker betaling",whereKey:"Hvor skal licensnøglen sendes?",emailLabel:"E-mail til licensnøglen",emailHint:"Vi sender nøglen efter betaling og viser den på næste side. Indsæt den i udvidelsen.",continueCheckout:"Fortsæt til sikker betaling",openingCheckout:"Åbner sikker betaling…",back:"← Tilbage",moneyBack:"14 dages returret",moneyBackDetail:"Ikke tilfreds? Fuld refundering.",secureCreem:"Sikker betaling med Creem",encrypted:"Krypteret sikker betaling via Creem.",noSubscription:"Intet abonnement",manageCancel:"Administrer eller opsig når som helst.",passAccess:"Én betaling. Fuld Pro i 3 dage.",lifetimeAccess:"Én betaling. Brug for altid.",guarantees:"Købsgarantier",invalidEmail:"Indtast e-mailen til din nøgle.",checkoutError:"Kunne ikke starte betalingen.",genericError:"Noget gik galt." },
  no: { ...en, trusted:"Betrodd av",user:"bruker",users:"brukere",chooseAccess:"Velg tilgang",choosePlan:"Velg plan",pass:"🔥 3-dagerspass",oneTime:"Engangsbetaling",monthly:"Månedlig",cancelAnytime:"Avslutt når som helst",recommended:"Anbefalt",lifetime:"Livstid",forever:"Én betaling · for alltid",getPass:"Få 3 dagers tilgang",startMonthly:"Start månedlig",getLifetime:"Få livstidstilgang",perMonth:"/mnd.",secureInstant:"Sikker betaling · Umiddelbar tilgang",secureCheckout:"Sikker betaling",whereKey:"Hvor skal lisensnøkkelen sendes?",emailLabel:"E-post for lisensnøkkelen",emailHint:"Vi sender nøkkelen etter betaling og viser den på neste side. Lim den inn i utvidelsen.",continueCheckout:"Fortsett til sikker betaling",openingCheckout:"Åpner sikker betaling…",back:"← Tilbake",moneyBack:"14 dagers pengene tilbake",moneyBackDetail:"Ikke fornøyd? Full refusjon.",secureCreem:"Sikker betaling med Creem",encrypted:"Kryptert sikker betaling via Creem.",noSubscription:"Ingen abonnement",manageCancel:"Administrer eller avslutt når som helst.",passAccess:"Én betaling. Full Pro i 3 dager.",lifetimeAccess:"Én betaling. Bruk for alltid.",guarantees:"Kjøpsgarantier",invalidEmail:"Skriv inn e-posten for nøkkelen.",checkoutError:"Kunne ikke starte betalingen.",genericError:"Noe gikk galt." },
  fi: { ...en, trusted:"Luottanut",user:"käyttäjä",users:"käyttäjää",chooseAccess:"Valitse käyttöoikeus",choosePlan:"Valitse paketti",pass:"🔥 3 päivän passi",oneTime:"Kertamaksu",monthly:"Kuukausittainen",cancelAnytime:"Peru milloin tahansa",recommended:"Suositeltu",lifetime:"Elinikäinen",forever:"Yksi maksu · ikuisesti",getPass:"Hanki 3 päivän käyttö",startMonthly:"Aloita kuukausitilaus",getLifetime:"Hanki elinikäinen käyttö",perMonth:"/kk",secureInstant:"Turvallinen maksu · Välitön käyttö",secureCheckout:"Turvallinen maksu",whereKey:"Minne lisenssiavain lähetetään?",emailLabel:"Lisenssiavaimen sähköposti",emailHint:"Lähetämme avaimen maksun jälkeen ja näytämme sen seuraavalla sivulla. Liitä se laajennukseen.",continueCheckout:"Jatka turvalliseen maksuun",openingCheckout:"Avataan maksua…",back:"← Takaisin",moneyBack:"14 päivän palautusoikeus",moneyBackDetail:"Etkö ole tyytyväinen? Täysi hyvitys.",secureCreem:"Turvallinen Creem-maksu",encrypted:"Creem käsittelee salatun turvallisen maksun.",noSubscription:"Ei tilausta",manageCancel:"Hallitse tai peru milloin tahansa.",passAccess:"Yksi maksu. Täysi Pro 3 päiväksi.",lifetimeAccess:"Yksi maksu. Käytä ikuisesti.",guarantees:"Ostoturva",invalidEmail:"Anna sähköposti avaimen lähettämistä varten.",checkoutError:"Maksua ei voitu aloittaa.",genericError:"Jokin meni vikaan." },
  cs: { ...en, trusted:"Důvěřuje nám",user:"uživatel",users:"uživatelů",chooseAccess:"Vyberte přístup",choosePlan:"Vyberte plán",pass:"🔥 Přístup na 3 dny",oneTime:"Jednorázová platba",monthly:"Měsíčně",cancelAnytime:"Kdykoli zrušit",recommended:"Doporučeno",lifetime:"Doživotně",forever:"Jedna platba · navždy",getPass:"Získat přístup na 3 dny",startMonthly:"Spustit měsíční plán",getLifetime:"Získat doživotní přístup",perMonth:"/měs.",secureInstant:"Bezpečná platba · Okamžitý přístup",secureCheckout:"Bezpečná platba",whereKey:"Kam máme poslat licenční klíč?",emailLabel:"E-mail pro licenční klíč",emailHint:"Po platbě klíč pošleme e-mailem a ukážeme na další stránce. Vložte ho do rozšíření.",continueCheckout:"Pokračovat k bezpečné platbě",openingCheckout:"Otevírání platby…",back:"← Zpět",moneyBack:"14denní vrácení peněz",moneyBackDetail:"Nejste spokojeni? Plná náhrada.",secureCreem:"Bezpečná platba přes Creem",encrypted:"Šifrovaná bezpečná platba přes Creem.",noSubscription:"Bez předplatného",manageCancel:"Předplatné lze kdykoli spravovat či zrušit.",passAccess:"Jedna platba. Plný Pro přístup na 3 dny.",lifetimeAccess:"Jedna platba. Používejte navždy.",guarantees:"Záruky nákupu",invalidEmail:"Zadejte e-mail pro zaslání klíče.",checkoutError:"Platbu se nepodařilo spustit.",genericError:"Něco se pokazilo." },
  ro: { ...en, trusted:"De încredere pentru",user:"utilizator",users:"utilizatori",chooseAccess:"Alege accesul",choosePlan:"Alege un plan",pass:"🔥 Acces pentru 3 zile",oneTime:"Plată unică",monthly:"Lunar",cancelAnytime:"Anulezi oricând",recommended:"Recomandat",lifetime:"Pe viață",forever:"O plată · pentru totdeauna",getPass:"Obține acces pentru 3 zile",startMonthly:"Începe lunar",getLifetime:"Obține acces pe viață",perMonth:"/lună",secureInstant:"Plată sigură · Acces instant",secureCheckout:"Plată sigură",whereKey:"Unde trimitem cheia de licență?",emailLabel:"Email pentru cheia de licență",emailHint:"Trimitem cheia după plată și o afișăm pe pagina următoare. Lipește-o în extensie pentru activare.",continueCheckout:"Continuă la plata sigură",openingCheckout:"Se deschide plata…",back:"← Înapoi",moneyBack:"Banii înapoi în 14 zile",moneyBackDetail:"Nu ești mulțumit? Rambursare integrală.",secureCreem:"Plată sigură prin Creem",encrypted:"Plată criptată și sigură procesată de Creem.",noSubscription:"Fără abonament",manageCancel:"Gestionează sau anulează oricând.",passAccess:"O plată. Acces Pro complet 3 zile.",lifetimeAccess:"O plată. Folosește pentru totdeauna.",guarantees:"Garanții de cumpărare",invalidEmail:"Introdu emailul pentru trimiterea cheii.",checkoutError:"Plata nu a putut fi pornită.",genericError:"Ceva nu a mers." },
  hu: { ...en, trusted:"Megbízik benne",user:"felhasználó",users:"felhasználó",chooseAccess:"Válassz hozzáférést",choosePlan:"Válassz csomagot",pass:"🔥 3 napos hozzáférés",oneTime:"Egyszeri fizetés",monthly:"Havi",cancelAnytime:"Bármikor lemondható",recommended:"Ajánlott",lifetime:"Élettartam",forever:"Egy fizetés · örökre",getPass:"3 napos hozzáférés kérése",startMonthly:"Havi csomag indítása",getLifetime:"Élettartam-hozzáférés",perMonth:"/hó",secureInstant:"Biztonságos fizetés · Azonnali hozzáférés",secureCheckout:"Biztonságos fizetés",whereKey:"Hová küldjük a licenckulcsot?",emailLabel:"E-mail a licenckulcshoz",emailHint:"Fizetés után elküldjük és a következő oldalon megmutatjuk a kulcsot. Illeszd be a bővítménybe.",continueCheckout:"Tovább a biztonságos fizetéshez",openingCheckout:"Fizetés megnyitása…",back:"← Vissza",moneyBack:"14 napos pénzvisszatérítés",moneyBackDetail:"Nem elégedett? Teljes visszatérítés.",secureCreem:"Biztonságos Creem-fizetés",encrypted:"Titkosított biztonságos fizetés a Creemen keresztül.",noSubscription:"Nincs előfizetés",manageCancel:"Bármikor kezelhető vagy lemondható.",passAccess:"Egy fizetés. Teljes Pro 3 napig.",lifetimeAccess:"Egy fizetés. Használd örökre.",guarantees:"Vásárlási garanciák",invalidEmail:"Add meg az e-mailt a kulcs elküldéséhez.",checkoutError:"A fizetés nem indítható.",genericError:"Hiba történt." },
  tr: { ...en, trusted:"Güvenen",user:"kullanıcı",users:"kullanıcı",chooseAccess:"Erişiminizi seçin",choosePlan:"Plan seçin",pass:"🔥 3 Günlük Geçiş",oneTime:"Tek seferlik ödeme",monthly:"Aylık",cancelAnytime:"İstediğiniz zaman iptal",recommended:"Önerilen",lifetime:"Ömür boyu",forever:"Tek ödeme · sonsuza dek",getPass:"3 Günlük Erişim Al",startMonthly:"Aylık başlat",getLifetime:"Ömür Boyu Erişim Al",perMonth:"/ay",secureInstant:"Güvenli ödeme · Anında erişim",secureCheckout:"Güvenli ödeme",whereKey:"Lisans anahtarını nereye gönderelim?",emailLabel:"Lisans anahtarı e-postası",emailHint:"Ödemeden sonra anahtarı e-postayla gönderir ve sonraki sayfada gösteririz. Etkinleştirmek için uzantıya yapıştırın.",continueCheckout:"Güvenli ödemeye devam et",openingCheckout:"Ödeme açılıyor…",back:"← Geri",moneyBack:"14 gün para iadesi",moneyBackDetail:"Memnun değil misiniz? Tam iade.",secureCreem:"Creem ile güvenli ödeme",encrypted:"Creem tarafından işlenen şifreli güvenli ödeme.",noSubscription:"Abonelik yok",manageCancel:"Aboneliği istediğiniz zaman yönetin veya iptal edin.",passAccess:"Tek ödeme. 3 gün tam Pro erişimi.",lifetimeAccess:"Tek ödeme. Sonsuza dek kullanın.",guarantees:"Satın alma garantileri",invalidEmail:"Anahtarın gönderileceği e-postayı girin.",checkoutError:"Ödeme başlatılamadı.",genericError:"Bir şeyler ters gitti." },
  id: { ...en, trusted:"Dipercaya oleh",user:"pengguna",users:"pengguna",chooseAccess:"Pilih akses",choosePlan:"Pilih paket",pass:"🔥 Akses 3 Hari",oneTime:"Sekali bayar",monthly:"Bulanan",cancelAnytime:"Batalkan kapan saja",recommended:"Direkomendasikan",lifetime:"Seumur hidup",forever:"Satu pembayaran · selamanya",getPass:"Dapatkan Akses 3 Hari",startMonthly:"Mulai Bulanan",getLifetime:"Dapatkan Akses Seumur Hidup",perMonth:"/bln",secureInstant:"Pembayaran aman · Akses instan",secureCheckout:"Pembayaran aman",whereKey:"Ke mana kunci lisensi dikirim?",emailLabel:"Email untuk kunci lisensi",emailHint:"Kami mengirim kunci setelah pembayaran dan menampilkannya di halaman berikutnya. Tempelkan ke ekstensi untuk aktivasi.",continueCheckout:"Lanjut ke pembayaran aman",openingCheckout:"Membuka pembayaran…",back:"← Kembali",moneyBack:"Garansi uang kembali 14 hari",moneyBackDetail:"Tidak puas? Pengembalian dana penuh.",secureCreem:"Pembayaran aman oleh Creem",encrypted:"Pembayaran terenkripsi dan aman melalui Creem.",noSubscription:"Tanpa langganan",manageCancel:"Kelola atau batalkan kapan saja.",passAccess:"Satu pembayaran. Pro penuh selama 3 hari.",lifetimeAccess:"Satu pembayaran. Gunakan selamanya.",guarantees:"Jaminan pembelian",invalidEmail:"Masukkan email tujuan kunci lisensi.",checkoutError:"Pembayaran tidak dapat dimulai.",genericError:"Terjadi kesalahan." },
  vi: { ...en, trusted:"Được tin dùng bởi",user:"người dùng",users:"người dùng",chooseAccess:"Chọn quyền truy cập",choosePlan:"Chọn gói",pass:"🔥 Gói 3 ngày",oneTime:"Thanh toán một lần",monthly:"Hàng tháng",cancelAnytime:"Hủy bất cứ lúc nào",recommended:"Đề xuất",lifetime:"Trọn đời",forever:"Thanh toán một lần · dùng mãi mãi",getPass:"Nhận quyền truy cập 3 ngày",startMonthly:"Bắt đầu gói tháng",getLifetime:"Nhận quyền truy cập trọn đời",perMonth:"/tháng",secureInstant:"Thanh toán an toàn · Truy cập ngay",secureCheckout:"Thanh toán an toàn",whereKey:"Gửi khóa bản quyền đến đâu?",emailLabel:"Email nhận khóa bản quyền",emailHint:"Chúng tôi gửi khóa sau thanh toán và hiển thị ở trang tiếp theo. Dán khóa vào tiện ích để kích hoạt.",continueCheckout:"Tiếp tục thanh toán an toàn",openingCheckout:"Đang mở thanh toán…",back:"← Quay lại",moneyBack:"Hoàn tiền trong 14 ngày",moneyBackDetail:"Không hài lòng? Hoàn tiền đầy đủ.",secureCreem:"Thanh toán an toàn qua Creem",encrypted:"Thanh toán mã hóa an toàn do Creem xử lý.",noSubscription:"Không đăng ký",manageCancel:"Quản lý hoặc hủy bất cứ lúc nào.",passAccess:"Một lần thanh toán. Pro đầy đủ trong 3 ngày.",lifetimeAccess:"Một lần thanh toán. Dùng mãi mãi.",guarantees:"Bảo đảm mua hàng",invalidEmail:"Nhập email để nhận khóa bản quyền.",checkoutError:"Không thể bắt đầu thanh toán.",genericError:"Đã xảy ra lỗi." },
  ar: { ...en, trusted:"يثق به",user:"مستخدم",users:"مستخدمين",chooseAccess:"اختر الوصول",choosePlan:"اختر خطة",pass:"🔥 وصول لمدة 3 أيام",oneTime:"دفعة واحدة",monthly:"شهري",cancelAnytime:"إلغاء في أي وقت",recommended:"موصى به",lifetime:"مدى الحياة",forever:"دفعة واحدة · للأبد",getPass:"احصل على وصول 3 أيام",startMonthly:"ابدأ شهريًا",getLifetime:"احصل على وصول مدى الحياة",perMonth:"/شهر",secureInstant:"دفع آمن · وصول فوري",secureCheckout:"دفع آمن",whereKey:"أين نرسل مفتاح الترخيص؟",emailLabel:"البريد الإلكتروني لمفتاح الترخيص",emailHint:"نرسل المفتاح بعد الدفع ونُظهره في الصفحة التالية. الصقه في الإضافة للتفعيل.",continueCheckout:"المتابعة إلى الدفع الآمن",openingCheckout:"جارٍ فتح الدفع…",back:"رجوع →",moneyBack:"استرداد خلال 14 يومًا",moneyBackDetail:"غير راضٍ؟ استرداد كامل.",secureCreem:"دفع آمن عبر Creem",encrypted:"دفع مشفر وآمن تتم معالجته بواسطة Creem.",noSubscription:"بدون اشتراك",manageCancel:"إدارة الاشتراك أو إلغاؤه في أي وقت.",passAccess:"دفعة واحدة. وصول Pro كامل لمدة 3 أيام.",lifetimeAccess:"دفعة واحدة. استخدام للأبد.",guarantees:"ضمانات الشراء",invalidEmail:"أدخل البريد لإرسال مفتاح الترخيص.",checkoutError:"تعذر بدء الدفع.",genericError:"حدث خطأ." },
  he: { ...en, trusted:"בשימוש אצל",user:"משתמש",users:"משתמשים",chooseAccess:"בחירת גישה",choosePlan:"בחירת תוכנית",pass:"🔥 גישה ל־3 ימים",oneTime:"תשלום חד־פעמי",monthly:"חודשי",cancelAnytime:"ביטול בכל עת",recommended:"מומלץ",lifetime:"לכל החיים",forever:"תשלום אחד · לתמיד",getPass:"קבלת גישה ל־3 ימים",startMonthly:"התחלת מנוי חודשי",getLifetime:"קבלת גישה לכל החיים",perMonth:"/חודש",secureInstant:"תשלום מאובטח · גישה מיידית",secureCheckout:"תשלום מאובטח",whereKey:"לאן לשלוח את מפתח הרישיון?",emailLabel:"אימייל למפתח הרישיון",emailHint:"נשלח את המפתח לאחר התשלום ונציג אותו בעמוד הבא. יש להדביק אותו בתוסף להפעלה.",continueCheckout:"המשך לתשלום מאובטח",openingCheckout:"פותח תשלום…",back:"חזרה →",moneyBack:"החזר כספי תוך 14 יום",moneyBackDetail:"לא מרוצים? החזר מלא.",secureCreem:"תשלום מאובטח עם Creem",encrypted:"תשלום מוצפן ומאובטח בעיבוד Creem.",noSubscription:"ללא מנוי",manageCancel:"ניהול או ביטול בכל עת.",passAccess:"תשלום אחד. גישת Pro מלאה ל־3 ימים.",lifetimeAccess:"תשלום אחד. שימוש לתמיד.",guarantees:"הבטחות רכישה",invalidEmail:"יש להזין אימייל לשליחת המפתח.",checkoutError:"לא ניתן להתחיל בתשלום.",genericError:"אירעה שגיאה." },
  th: { ...en, trusted:"ได้รับความไว้วางใจจาก",user:"ผู้ใช้",users:"ผู้ใช้",chooseAccess:"เลือกสิทธิ์ใช้งาน",choosePlan:"เลือกแพ็กเกจ",pass:"🔥 แพ็กเกจ 3 วัน",oneTime:"ชำระครั้งเดียว",monthly:"รายเดือน",cancelAnytime:"ยกเลิกได้ทุกเมื่อ",recommended:"แนะนำ",lifetime:"ตลอดชีพ",forever:"จ่ายครั้งเดียว · ใช้ได้ตลอด",getPass:"รับสิทธิ์ 3 วัน",startMonthly:"เริ่มรายเดือน",getLifetime:"รับสิทธิ์ตลอดชีพ",perMonth:"/เดือน",secureInstant:"ชำระเงินปลอดภัย · ใช้งานทันที",secureCheckout:"ชำระเงินปลอดภัย",whereKey:"ให้ส่งคีย์ใบอนุญาตไปที่ไหน?",emailLabel:"อีเมลสำหรับคีย์ใบอนุญาต",emailHint:"เราจะส่งคีย์หลังชำระเงินและแสดงในหน้าถัดไป ให้วางคีย์ในส่วนขยายเพื่อเปิดใช้งาน",continueCheckout:"ไปยังการชำระเงินที่ปลอดภัย",openingCheckout:"กำลังเปิดการชำระเงิน…",back:"← กลับ",moneyBack:"คืนเงินภายใน 14 วัน",moneyBackDetail:"ไม่พอใจ? รับเงินคืนเต็มจำนวน",secureCreem:"ชำระเงินปลอดภัยผ่าน Creem",encrypted:"Creem ประมวลผลการชำระเงินแบบเข้ารหัสและปลอดภัย",noSubscription:"ไม่มีการสมัครสมาชิก",manageCancel:"จัดการหรือยกเลิกได้ทุกเมื่อ",passAccess:"จ่ายครั้งเดียว ใช้ Pro เต็มรูปแบบ 3 วัน",lifetimeAccess:"จ่ายครั้งเดียว ใช้ได้ตลอด",guarantees:"การรับประกันการซื้อ",invalidEmail:"กรอกอีเมลสำหรับส่งคีย์ใบอนุญาต",checkoutError:"เริ่มการชำระเงินไม่ได้",genericError:"เกิดข้อผิดพลาด" },
};

Object.assign(COPY.es, {
  allExtensions: "Todas las extensiones",
  viewStore: "Ver en Chrome Web Store",
  privacyPolicy: "Política de privacidad",
  showMore: "Mostrar más",
  showLess: "Mostrar menos",
  extensionDetected: "Extensión detectada · Ya instalada",
});
Object.assign(COPY.es_419, COPY.es);

export function purchaseCopy(locale: Locale): PurchaseCopy {
  return COPY[locale];
}
